---

# Deduction rate
rate:
  value: 
    '2014': 0.0
    '2018': 0.2
    '2026': 0.23

# Taxable income phaseout threshold for SSTBs, single filers
po_thresh_sstb_single:
  value: 157500
  i_measure: default
  i_base_year: 
    '2018': 2017
    '2026': 2025
  i_direction: default
  i_increment: default

# Taxable income phaseout threshold for non-SSTBs, single filers
po_thresh_non_sstb_single:
  value: 157500
  i_measure: default
  i_base_year: 
    '2018': 2017
    '2026': 2025
  i_direction: default
  i_increment: default
  
# Share of ordinary taxable income limit
txbl_inc_limit:
  value: 
    '2017': 0.2
    '2026': 0.22

# Whether QBI deduction doesn't have a set phase out
no_po:
  value: 
    '2017': 0
    '2026': 1
