#!/bin/bash
#-----------------------------------------------------------------------
# launch_sigma_calib.sh  --  run the sigma sweep grid.
#
# Three full-sample vintages, one per trial sigma, each with its own baseline. The
# grid, the behavior alternatives and the runscripts are generated by
#
#   python3 other/top_tax/sigma_calib/write_sigma_sweep.py [--charity 50|100]
#
# CHARITY MATTERS HERE. The shipped sigma of 0.16 was derived under charity/100,
# product runs use charity/50, and that mismatch is a dated waiver on the entry.
# Passing 100 sets up a reproduction of the shipped value; passing 50 is the
# deferred re-derivation, which is EXPECTED to move it.
#
# delete_detail=0 on every leg: the ETI needs baseline static, shock static and
# shock conventional detail, plus the shock's kg_dynamics_state for the gate
# thresholds.
#
# Submit through the sbatch wrapper, not from the login node -- slurm_run.sh's
# Phase 0 runs setup.R in process.
#
#   sbatch other/top_tax/sigma_calib/launch_sigma_calib.sbatch [charity] [tag ...]
#
# Then measure and write the value:
#   sbatch other/top_tax/sigma_calib/measure_sigma.sbatch [charity]
#-----------------------------------------------------------------------
set -euo pipefail
cd /nfs/roberts/project/pi_nrs36/jar335/Repositories/Tax-Simulator

CHARITY="${1:-100}"
shift || true
case "$CHARITY" in 50|100) ;; *) echo "charity must be 50 or 100, got '$CHARITY'"; exit 1;; esac

ALL_TAGS=(00 16 30)
VINTAGE_SUFFIX="${VINTAGE_SUFFIX:-}"

if [ "$#" -gt 0 ]; then TAGS=("$@"); else TAGS=("${ALL_TAGS[@]}"); fi

for tag in "${TAGS[@]}"; do
  runscript="tests/sigma_calib_${CHARITY}_conv_${tag}"
  vintage="sigma_calib_${CHARITY}_conv_${tag}${VINTAGE_SUFFIX}"

  if [ ! -f "config/runscripts/${runscript}.csv" ]; then
    echo "No runscript at config/runscripts/${runscript}.csv."
    echo "Generate the grid first:"
    echo "  python3 other/top_tax/sigma_calib/write_sigma_sweep.py --charity ${CHARITY}"
    exit 1
  fi

  echo "launching sigma calib: charity/${CHARITY} tag ${tag} -> ${runscript}, vintage ${vintage}"
  bash slurm_run.sh "$runscript" NULL 1 "$vintage" 1 0 NULL 0
done

echo ""
echo "${#TAGS[@]} sigma vintage(s) launched at charity/${CHARITY}. When all reach Phase 3b:"
echo "  sbatch other/top_tax/sigma_calib/measure_sigma.sbatch ${CHARITY}"
