---

# Whether tipped income is deductible from gross income
tip_deduction:
  value: 
    '2014': 0
    '2025': 1

# Whether tips deduction is limited to leisure and hospitality workers only
tip_deduction_lh:
  value:
    '2014': 0
    '2025': 1