---
# Personal exemption value
value:
  value:
    '2014': 2000
  i_measure:
    '1986': cpi
    '2017': chained_cpi
  i_base_year: 1988
  i_direction: -1
  i_increment: 50

# Phaseout threshold, single filers
po_thresh_single:
  value:
    '2014': 250000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# Phaseout threshold, joint filers  
po_thresh_married:
  value:
    '2014': 300000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default  
 
# Phaseout threshold, head-of-household filers
po_thresh_head:
  value:
    '2014': 275000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
# Whether dependents qualify for exemptions
nondep_qualify:
  value:
    '2014': 1
    '2018': 0
