---

# Whether CTC (exlcluding Credit for Other Dependent) is fully refundable
fully_refundable:
  value:
    '2014': 0
    '2021': 1
    '2022': 0 
    '2024': 1
    
# Maximum refundable CTC per qualifying child
max_refund:
  value:
    '2014': Inf
    '2018': 1400
    '2021': Inf
    '2022': 1400
    '2024': Inf
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year: 2017
  i_direction: -1
  i_increment: 100

