---

filing_status_mapper:
  pease_thresh:
    '1': pease_thresh_single
    '2': pease_thresh_married
    '3': pease_thresh_married / 2
    '4': pease_thresh_head
  salt_limit:
    '1': salt_limit_married / 2
    '2': salt_limit_married
    '3': salt_limit_married / 2
    '4': salt_limit_married / 2
  mort_bal_limit:
    '1': mort_bal_limit_single
    '2': mort_bal_limit_married
    '3': mort_bal_limit_mfs
    '4': mort_bal_limit_single

# Maximum deductible state and local taxes, joint returns
salt_limit_married:
  value:
    '2014': Inf
    '2018': 10000
    '2026': 150000

# Years after which mortgage interest deduction is limited based on mortgage balance. Maps to mort_bal_limit 
mort_bal_limit_years:
  value: 
    '2014': [1987, Inf]
    '2018': [1987, 2017, Inf]

# Limitations on deductible mortgage interest based on mortgage balance, single filers
mort_bal_limit_single:
  value:
    '2014': [Inf, 1000000]
    '2018': [Inf, 1000000, 375000]

# Limitations on deductible mortgage interest based on mortgage balance, joint filers
mort_bal_limit_married:
  value:
    '2014': [Inf, 1000000]
    '2018': [Inf, 1000000, 750000]

# Limitations on deductible mortgage interest based on mortgage balance, married filing separately filers
mort_bal_limit_mfs:
  value:
    '2014': [Inf, 500000]
    '2018': [Inf, 500000, 375000]

# Maximum deductible "miscellanous" itemized deductions
misc_limit:
  value:
    '2014': Inf
    '2018': 0

# Maximum deductible casualty and loss expenses
casualty_limit:
  value: 
    '2014': Inf
    '2018': 0
    
# AGI threshold above which itemized deductions are limited under Pease, single filers
pease_thresh_single:
  value:
    '2014': 250000
    '2018': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# AGI threshold above which itemized deductions are limited under Pease, joint filers  
pease_thresh_married:
  value:
    '2014': 300000
    '2018': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default  
 
# AGI threshold above which itemized deductions are limited under Pease, head-of-household filers
pease_thresh_head:
  value:
    '2014': 275000
    '2018': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
