#!/bin/bash
#-----------------------------------------------------------------------
# launch_timeable.sh  --  run the short-run retiming-share sweep.
#
# Three full-sample vintages, one per trial share. Each runs the delayed shock (gains
# rate announced 2026, effective 2027) plus a permanent leg that sanity-checks the
# long-run moment has not moved. The grid, the behavior alternatives and the
# runscripts are generated by
#
#   python3 other/kg_model_tests/form_ab/write_bathtub_sweep.py timeable_logs
#   python3 other/kg_model_tests/form_ab/write_bathtub_sweep.py timeable      # levels
#
# WHAT REPLACED WHAT. launch_timeable_logs.sh set the trial share by exporting
# KG_TIMEABLE_SHARE_LOGS, KG_ETA_LOGS and KG_RESPONSE_FORM into the submitting shell,
# and passed the `user_id` argument retired on 2026-07-25. Both back doors are gone,
# so it had been unrunnable for a fortnight. It also took ONE share per invocation and
# expected the operator to iterate by hand until the moment came within 5% of target.
# This takes the whole grid, and measure_timeable.R interpolates.
#
# delete_detail=0: the measurement reads this vintage's own baseline static detail
# plus the delayed and permanent legs' conventional detail, at three different years.
# There is no shared-baseline shortcut here the way the eta dial has one.
#
# eta MUST BE PINNED FIRST. The share is identified given eta, because the long-run
# moment is share-invariant while the short-run one is not. measure_timeable.R checks
# that invariance across the grid rather than trusting it.
#
# Submit through the sbatch wrapper, not from the login node -- slurm_run.sh's
# Phase 0 runs setup.R in process:
#
#   sbatch other/kg_model_tests/form_ab/launch_timeable.sbatch [logs|levels] [tag ...]
#
# Then measure and write the value:
#   sbatch other/kg_model_tests/form_ab/measure_timeable.sbatch [logs|levels]
#-----------------------------------------------------------------------
set -euo pipefail
cd /nfs/roberts/project/pi_nrs36/jar335/Repositories/Tax-Simulator

SETTINGS=config/calibrations/kg/settings.yaml

FORM="${1:-logs}"
shift || true
case "$FORM" in logs|levels) ;; *) echo "form must be logs or levels, got '$FORM'"; exit 1;; esac

# Refuse to run under the wrong response form. Reading the setting rather than
# trusting the operator: a sweep run under the other form measures the other model,
# and the number would look perfectly reasonable.
live=$(grep -A1 '^response_form:' "$SETTINGS" | grep -oP '^\s+value:\s*\K\S+')
if [ "$live" != "$FORM" ]; then
  cat <<EOF
response_form is '$live' in $SETTINGS, and this sweep needs '$FORM'.

The setting is fixed for the whole run on purpose: each response form has its own
calibrated share, so a run cannot mix them.

  1. set  response_form: $FORM  in $SETTINGS
  2. re-run this script
  3. set it back to 'logs' when the measurement is done

Step 3 matters if you changed it. Leaving it on 'levels' silently changes every
capital-gains scenario the model runs afterwards.
EOF
  exit 1
fi

if [ "$FORM" = logs ]; then STEM=form_timeable_logs; else STEM=form_timeable_levels; fi

ALL_TAGS=(15 25 40)
VINTAGE_SUFFIX="${VINTAGE_SUFFIX:-}"

if [ "$#" -gt 0 ]; then TAGS=("$@"); else TAGS=("${ALL_TAGS[@]}"); fi

for tag in "${TAGS[@]}"; do
  runscript="tests/${STEM}_${tag}"
  vintage="${STEM}_${tag}${VINTAGE_SUFFIX}"

  if [ ! -f "config/runscripts/${runscript}.csv" ]; then
    echo "No runscript at config/runscripts/${runscript}.csv."
    echo "Generate the grid first:"
    if [ "$FORM" = logs ]; then
      echo "  python3 other/kg_model_tests/form_ab/write_bathtub_sweep.py timeable_logs"
    else
      echo "  python3 other/kg_model_tests/form_ab/write_bathtub_sweep.py timeable"
    fi
    exit 1
  fi

  echo "launching timeable sweep ($FORM): tag ${tag} -> ${runscript}, vintage ${vintage}"
  bash slurm_run.sh "$runscript" NULL 1 "$vintage" 1 0 NULL 0
done

echo ""
echo "${#TAGS[@]} timeable vintage(s) launched ($FORM). When all reach Phase 3b:"
echo "  sbatch other/kg_model_tests/form_ab/measure_timeable.sbatch $FORM"
