#!/bin/bash
#-----------------------------------------------------------------------
# launch_eta_dial_logs.sh  --  Part B1 driver (pin eta_tilde for the logs form).
#
# Runs the +5pp capital-gains shock (s_cg_r25, against its own baseline) at three
# trial eta_tilde values under the net-of-tax response form, so that
# measure_efull_logs.R can measure E_full at each and invert for the eta_tilde
# that hits the target moment.
#
# WHAT CHANGED, 2026-07-26. This script used to set the trial value by exporting
# KG_ETA_LOGS / KG_RESPONSE_FORM / KG_TIMEABLE_SHARE_LOGS into the submitting
# shell and letting the sbatch phases inherit them. Those back doors are retired:
# a value reaching the model through the environment leaves no trace in the vintage
# it produced, so a shipped number and the run behind it could drift apart with
# nothing to notice. A trial value is now a FILE, bound by its own behavior
# alternative, named by its own runscript -- all three generated by
#
#   python3 other/kg_model_tests/form_ab/write_eta_sweep.py logs
#
# which is also where the grid itself is declared. The response form is no longer
# set here at all: it is `logs` in config/calibrations/kg/settings.yaml, and the
# calibrations record that they were derived under it, so a run under the other
# form stops rather than quietly mixing the two. The provisional timeable share
# (0.2542) likewise just travels in the sweep file, unchanged from the shipped
# value, because the long-run moment is timeable-share invariant.
#
# Full sample; delete_detail=1 keeps the conventional_no_wealth leg (the E_full
# numerator R_shock). measure_efull_logs.R pulls the form-INVARIANT base R and the
# shared-law dtau from the levels central vintage eta_dial_c_v2 (kept with full
# detail), so no logs-side baseline/conventional detail is needed here.
#
# After all three finish (Phase 2N/3b), measure + invert:
#   sbatch other/kg_model_tests/form_ab/measure_efull_logs.sbatch
#
# SUBMIT THIS THROUGH ITS SBATCH WRAPPER, not from the login node:
#
#   sbatch other/kg_model_tests/form_ab/launch_eta_dial_logs.sbatch [tag ...]
#
# slurm_run.sh's Phase 0 runs setup.R in process -- parsing globals, reading
# Tax-Data, serializing the configs -- which is real R work and does not belong on
# a login node.
#
# Usage (from repo root):
#   bash other/kg_model_tests/form_ab/launch_eta_dial_logs.sh          # whole grid
#   bash other/kg_model_tests/form_ab/launch_eta_dial_logs.sh 19       # one point
#
#   VINTAGE_SUFFIX=_spot bash other/kg_model_tests/form_ab/launch_eta_dial_logs.sh 19
#
# With no argument it launches the whole grid. With one or more tags it launches
# only those, which is what a spot check wants: re-run one point and confirm its
# detail file still matches the vintage already on scratch.
#
# VINTAGE_SUFFIX exists FOR that spot check, and it is not optional there. The
# vintage name is derived from the tag, so re-running tag 19 with no suffix would
# write straight over eta_dial_logs_19 -- destroying the very thing the spot check
# compares against, and turning a verification into an overwrite. With a suffix the
# re-run lands beside the original and the two can be diffed.
#-----------------------------------------------------------------------
set -euo pipefail
cd /nfs/roberts/project/pi_nrs36/jar335/Repositories/Tax-Simulator

# Trial grid straddling the expected eta_tilde* ~ 1.9 (net-of-tax elasticity
# matched to the same E_full = -2.52 local moment as the levels form). Each
# vintage runs its own baseline (NULL) so the three are independent and run
# concurrently -- the levels eta-dial precedent (eta_dial_*_v2). The tags here,
# the generated runscripts, and measure_efull_logs.R's `runs` table all have to
# agree; the tag is the trial value with its decimal point dropped.
ALL_TAGS=(15 19 23)

# Appended to every vintage name this invocation writes. Empty by default, so a
# fresh grid lands on the names measure_efull_logs.R reads.
VINTAGE_SUFFIX="${VINTAGE_SUFFIX:-}"

if [ "$#" -gt 0 ]; then
  TAGS=("$@")
else
  TAGS=("${ALL_TAGS[@]}")
fi

for tag in "${TAGS[@]}"; do
  runscript="top_tax/eta_dial_logs_${tag}"
  vintage="eta_dial_logs_${tag}${VINTAGE_SUFFIX}"

  if [ ! -f "config/runscripts/${runscript}.csv" ]; then
    echo "No runscript at config/runscripts/${runscript}.csv."
    echo "Generate the grid first:"
    echo "  python3 other/kg_model_tests/form_ab/write_eta_sweep.py logs"
    exit 1
  fi

  echo "launching logs eta-dial: tag ${tag} -> runscript ${runscript}, vintage ${vintage}"
  bash slurm_run.sh "$runscript" NULL 1 "$vintage" 1 0 NULL 1
done

echo ""
echo "${#TAGS[@]} logs eta-dial vintage(s) launched. When all reach Phase 3b, run:"
echo "  sbatch other/kg_model_tests/form_ab/measure_efull_logs.sbatch"
