---

# Maximum deductible state and local taxes, joint returns
salt_limit_married:
  value:
    '2014': Inf
    '2018': 10000
    '2025': 40000
    '2026': 40400
    '2027': 40804
    '2028': 41212
    '2029': 41624
    '2030': 42040
    '2031': 42460
    '2032': 42885
    '2033': 43314
    '2034': 43747
    '2035': 44185
    '2036': 44627
    '2037': 45073
    '2038': 45524
    '2039': 45979
    '2040': 46439
    '2041': 46903
    '2042': 47372
    '2043': 47846
    '2044': 48324
    '2045': 48808
    '2046': 49296
    '2047': 49789
    '2048': 50287
    '2049': 50790
    '2050': 51298
    '2051': 51811
    '2052': 52329
    '2053': 52852
    '2054': 53381
    '2055': 53915
  
# Minimum value of SALT cap
salt_floor:
  value:
    '2014': 0
    '2025': 10000
    
# Income above which SALT deduction phases out towards the floor
salt_floor_thresh:
  value:
    '2014': Inf
    '2025': 500000
    '2026': 505000
    '2027': 510050
    '2028': 515151
    '2029': 520302
    '2030': 525505
    '2031': 530760
    '2032': 536068
    '2033': 541428
    '2034': 546842
    '2035': 552311
    '2036': 557834
    '2037': 563412
    '2038': 569046
    '2039': 574736
    '2040': 580484
    '2041': 586289
    '2042': 592152
    '2043': 598074
    '2044': 604055
    '2045': 610095
    '2046': 616196
    '2047': 622358
    '2048': 628582
    '2049': 634868
    '2050': 641217
    '2051': 647629
    '2052': 654105
    '2053': 660646
    '2054': 667252
    '2055': 673925
  
# Years after which mortgage interest deduction is limited based on mortgage balance. Maps to mort_bal_limit 
mort_bal_limit_years:
  value: 
    '2014': [1987, Inf]
    '2018': [1987, 2017, Inf]

# Limitations on deductible mortgage interest based on mortgage balance, single filers
mort_bal_limit_single:
  value:
    '2014': [Inf, 1000000]
    '2018': [Inf, 1000000, 750000]

# Limitations on deductible mortgage interest based on mortgage balance, joint filers
mort_bal_limit_married:
  value:
    '2014': [Inf, 1000000]
    '2018': [Inf, 1000000, 750000]

# Limitations on deductible mortgage interest based on mortgage balance, married filing separately filers
mort_bal_limit_mfs:
  value:
    '2014': [Inf, 500000]
    '2018': [Inf, 500000, 375000]

# Maximum deductible "miscellanous" itemized deductions
misc_limit:
  value:
    '2014': Inf
    '2018': 0

# Maximum deductible casualty and loss expenses
casualty_limit:
  value: 
    '2014': Inf
    '2018': 0
    
# AGI threshold above which itemized deductions are limited under Pease, single filers
pease_thresh_single:
  value:
    '2014': 250000
    '2018': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# AGI threshold above which itemized deductions are limited under Pease, joint filers  
pease_thresh_married:
  value:
    '2014': 300000
    '2018': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default  
 
# AGI threshold above which itemized deductions are limited under Pease, head-of-household filers
pease_thresh_head:
  value:
    '2014': 275000
    '2018': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
# Tax value limitation reduction threshold, nonjoint returns (i.e. next bracket where rate corresponding to maximum tax value ends)
limit_tax_value_thresh_single:
  value:
    '2014': Inf
    '2026': 500000
  i_measure: default
  i_base_year:
    '2014': NA
    '2026': 2017
  i_direction: -1
  i_increment: 25
    
# Tax value limitation reduction threshold, joint returns (i.e. next bracket where rate corresponding to maximum tax value ends)
limit_tax_value_thresh_married:
  value:
    '2014': Inf
    '2026': 600000
  i_measure: default
  i_base_year:
    '2014': NA
    '2026': 2017
  i_direction: -1
  i_increment: 50
  
# Tax value limitation reduction rate, non-SALT (i.e. percentage point diference between maximum statutory tax value and target value) 
limit_tax_value_rate:
  value:
    '2014': 0
    '2026': 0.05405405
