---

# Whether SSN is required to qualify for CTC
need_ssn:
  value:
    '2014': 0

# Maximum credit value per "young" child
value_young:
  value: 
    '2014': [1000, 0]

# Maximum credit value per "old" child
value_old:
  value:
    '2014': [1000, 0]

# AGI threshold above which credit value phases out, single filers
po_thresh_single:
  value:
    '2014': [75000, Inf]
    
# AGI threshold above which credit value phases out, joint filers
po_thresh_married:
  value:
    '2014': [110000, Inf]
    
# AGI threshold above which credit value phases out, HoH filers
po_thresh_head:
  value:
    '2014': [75000, Inf]
    
# Maximum credit value per nonqualifying dependent (assumed to phaseout per po_thresh1)
value_other:
  value:
    '2014': 0

# Minimum refundable CTC per qualifying young child (i.e. y-intercept in trapezoid)
min_refund_young:
  value: 
    '2014': 0
  
# Minimum refundable CTC per qualifying old child (i.e. y-intercept in trapezoid)
min_refund_old:
  value: 
    '2014': 0

# Maximum refundable CTC per young qualifying child (inf implies maximum refund 
# is equal to the credit value)
max_refund_young:
  value:
    '2014': Inf
  
# Maximum refundable CTC per old qualifying child (inf implies maximum refund 
# is equal to the credit value)
max_refund_old:
  value:
    '2014': Inf

# Earned income threshold above which CTC phases in
pi_thresh:
  value:
    '2014': 3000
