---
indexation_defaults:
  i_measure:
    '1986': cpi
    '2017': chained_cpi
  i_base_year:
    '2014': 2017
  i_direction: 0
  i_increment: 1000

filing_status_mapper:
  kg_loss_limit:
    '1': kg_loss_limit_married
    '2': kg_loss_limit_married
    '3': kg_loss_limit_married / 2
    '4': kg_loss_limit_married
  bus_loss_limit:
    '1': bus_loss_limit_married
    '2': kg_loss_limit_married
    '3': kg_loss_limit_married / 2
    '4': kg_loss_limit_married

# Maxmimum deductible capital loss
kg_loss_limit_married:
  value: 3000
  
# Share of capital gains excluded from AGI
kg_excl_rate:
  value: 0
  
# Share of (current-law-taxable) interest income excluded from AGI
int_excl_rate:
  value: 0
  
# Share of (current-law-taxable) div excluded from AGI
div_excl_rate:
  value: 0

# Maximum deductible business loss
bus_loss_limit_married:
  value:
    '2014': Inf
    '2022': 500000
    '2027': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
# Year during and after which a divorce does not generate taxable/deductible alimony
alimony_repeal_year:
    value: 2018

  

