---
filing_status_mapper:
  above_limit:
    '1': above_limit_single
    '2': above_limit_single * 2
    '3': above_limit_single
    '4': above_limit_single

# AGI floor for itemized chariable deduction
item_floor_agi:
  value: 0

# Dollar-amount limit for itemized charitable deduction -- set to 0 for repeal
item_limit:
  value: Inf

# AGI limit for cash contributions, itemized deduction
item_cash_limit_agi:
  value:
    '2014': 0.5
    '2018': 0.6
    '2020': 1
    '2022': 0.6

# AGI limit for noncash contributions, itemized deduction
item_noncash_limit_agi:
  value:
    '2014': 0.3
    
# Maximum deductible above-the-line charitable contributions -- set to 0 for repeal
above_limit_single:
  value:
    '2014': 0
    '2020': 300
    '2022': 0
