---
indexation_defaults:
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year: 1995
  i_direction: 0
  i_increment: 10

filing_status_mapper:
  po_thresh_0:
    '1': po_thresh_0
    '2': po_thresh_0 + po_thresh_marriage_adj
    '3': po_thresh_0
    '4': po_thresh_0
  po_thresh_1:
    '1': po_thresh_1
    '2': po_thresh_1 + po_thresh_marriage_adj
    '3': po_thresh_1
    '4': po_thresh_1
  po_thresh_2:
    '1': po_thresh_2
    '2': po_thresh_2 + po_thresh_marriage_adj
    '3': po_thresh_2
    '4': po_thresh_2
  po_thresh_3:
    '1': po_thresh_3
    '2': po_thresh_3 + po_thresh_marriage_adj
    '3': po_thresh_3
    '4': po_thresh_3

pi_rate_0:
  value: 
    '2014': 0.0765
    '2021': 0.153
    '2022': 0.0765
  
pi_rate_1:
  value: 0.34
  
pi_rate_2:
  value: 0.4
  
pi_rate_3:
  value: 0.45
  
po_rate_0:
  value: 0.0765

po_rate_1:
  value: 0.1598
  
po_rate_2:
  value: 0.2106

po_rate_3:
  value: 0.2106
  
pi_end_0:
  value:
    '2014': 4220
    '2021': 9820
    '2022': 4220
  i_measure: default
  i_base_year:
    '2014': 1995
    '2021': 2020
    '2022': 1995
  i_direction: default
  i_increment: default
  
pi_end_1:
  value: 6330
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
pi_end_2:
  value: 8890
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
pi_end_3:
  value: 8890
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
po_thresh_0:
  value: 
    '2014': 5280
    '2021': 11610
    '2022': 5280
  i_measure: 
  i_base_year:
    '2014': 1995
    '2021': 2020
    '2022': 1995
  i_direction: default
  i_increment: default

po_thresh_1:
  value: 11610
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

po_thresh_2:
  value: 11610
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

po_thresh_3:
  value: 11610
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

po_thresh_marriage_adj:
  value: 5000
  i_measure: default
  i_base_year: 2008
  i_direction: default
  i_increment: default
  
inv_inc_limit:
  value: 
    '2014': 2200
    '2021': 10000
  i_measure: default
  i_base_year: 
    '2014': 1995
    '2021': 2020
  i_direction: -1
  i_increment: 50
  
min_age:
  value: 
    '2014': 25
    '2021': 19
    '2022': 25

max_age:
  value:
    '2014': 64
    '2021': Inf
    '2022': 64
