---
indexation_defaults:
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year:
    '2014': 2012
  i_direction: -1
  i_increment: 50

filing_status_mapper:
  pease_thresh:
    '1': pease_thresh_single
    '2': pease_thresh_married
    '3': pease_thresh_married / 2
    '4': pease_thresh_head
  salt_limit:
    '1': salt_limit_married
    '2': salt_limit_married
    '3': salt_limit_married / 2
    '4': salt_limit_married
  mort_bal_limit:
    '1': mort_bal_limit_single
    '2': mort_bal_limit_married
    '3': mort_bal_limit_mfs
    '4': mort_bal_limit_single

pease_thresh_single:
  value:
    '2014': 250000
    '2018': Inf
    '2026': 250000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
pease_thresh_married:
  value:
    '2014': 300000
    '2018': Inf
    '2026': 300000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default  
 
pease_thresh_head:
  value:
    '2014': 275000
    '2018': Inf
    '2026': 275000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
pease_rate:
  value: 0.03

pease_max:
  value: 0.8
  
med_floor_agi:
  value: 0.075

med_limit:
  value: Inf

salt_limit_married:
  value:
    '2014': Inf
    '2018': 10000
    '2026': Inf

mort_int_limit:
  value:
    '2014': Inf

mort_bal_limit_single:
  value:
    '2014': 1000000
    '2018': 375000
    '2026': 1000000

mort_bal_limit_married:
  value:
    '2014': 1000000
    '2018': 750000
    '2026': 1000000

mort_bal_limit_mfs:
  value:
    '2014': 500000
    '2018': 375000
    '2026': 500000

char_floor_agi:
  value: 0

char_limit:
  value: Inf

char_cash_limit_agi:
  value:
    '2014': 0.5
    '2018': 0.6
    '2020': 1
    '2022': 0.6

char_noncash_limit_agi:
  value:
    '2014': 0.3

casualty_limit:
  value: Inf

misc_floor_agi:
  value: 0.02
  
misc_limit:
  value:
    '2014': Inf
    '2018': 0
    '2026': Inf
