---
value:
  value:
    '2014': 2000
    '2018': 0
    '2026': 2000
  i_measure:
    '1986': cpi
    '2017': chained_cpi
  i_base_year: 1988
  i_direction: -1
  i_increment: 50

po_range_mfs:
  value: 62500
