---
indexation_defaults:
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year:
    '2014': 1987
    '2018': 2017
    '2026': 1987
  i_direction: -1
  i_increment: 50

filing_status_mapper:
  value:
    '1': value_single
    '2': value_single * 2
    '3': value_single
    '4': value_head
  old_blind_bonus:
    '1': old_blind_bonus_single
    '2': old_blind_bonus_married
    '3': old_blind_bonus_single
    '4': old_blind_bonus_single

value_single:
  value:
    '2014': 3000
    '2018': 12000
    '2026': 3000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
value_head:
  value:
    '2014': 4400
    '2018': 18000
    '2026': 4400
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

old_blind_bonus_single:
  value: 750
  i_measure: default
  i_base_year: 1987
  i_direction: default
  i_increment: default
  
old_blind_bonus_married:
  value: 600
  i_measure: default
  i_base_year: 1987
  i_direction: default
  i_increment: default
  
dep_floor:
  value: 500
  i_measure: default
  i_base_year: 1987
  i_direction: default
  i_increment: default
  
dep_earned_bonus:
  value: 250
  i_measure: default
  i_base_year: 1997
  i_direction: default
  i_increment: default
