---
#---------------
# Model version
#---------------

Tax-Simulator:
  type: model_data
  version: 1


#---------------------
# Dependency versions
#---------------------

Tax-Data:
  type: model_data
  version: 1
  default_vintage: 2024070817
  default_id: baseline

Macro-Projections: 
  type: model_data
  version: 3
  default_vintage: 2024100910
  default_id: baseline

Corporate-Tax-Model:
  type: model_data
  version: 1
  default_vintage: 2024021816
  default_id: baseline

Estate-Tax-Model:
  type: model_data
  version: 1
  default_vintage: 2024021614
  default_id: baseline
  
Value-Added-Tax-Model:
  type: model_data
  version: 1
  default_vintage: 2024050121
  default_id: baseline

Off-Model-Estimates:
  type: model_data
  version: 2
  default_vintage: 2024050122
  default_id: baseline
