---
#---------------
# Model version
#---------------

Tax-Simulator:
  type: model_data
  version: 1


#---------------------
# Dependency versions
#---------------------

Tax-Data:
  type: model_data
  version: 1
  default_vintage: '2025060316'
  default_id: baseline

Macro-Projections: 
  type: model_data
  version: 3
  default_vintage: '2025040115' 
  default_id: baseline

Value-Added-Tax-Model:
  type: model_data
  version: 1
  default_vintage: '2024050121'
  default_id: baseline

Off-Model-Estimates:
  type: model_data
  version: 4
  default_vintage: '20250603'
  default_id: baseline
  
Wealth-Tax-Simulator:
  type: model_data
  version: 1
  default_vintage: '2025011312'
  default_id: baseline

Cost-Recovery-Simulator:
  type: model_data
  version: 1
  default_vintage: '202505311850'
  default_id: baseline
  
Estate-Tax-Distribution:
  type: model_data
  version: 1
  default_vintage: '2025060917'
  default_id: baseline
  
Tariff-Model:
  type: model_data
  version: 1
  default_vintage: '2025060708'
  default_id: baseline

