---
filing_status_mapper:
  aoc_po_thresh:
    '1': aoc_po_thresh_single
    '2': aoc_po_thresh_single * 2
    '3': aoc_po_thresh_single
    '4': aoc_po_thresh_single
  aoc_po_range:
    '1': aoc_po_range_single
    '2': aoc_po_range_single * 2
    '3': aoc_po_range_single
    '4': aoc_po_range_single
  llc_po_thresh:
    '1': llc_po_thresh_single
    '2': llc_po_thresh_single * 2
    '3': llc_po_thresh_single
    '4': llc_po_thresh_single

aoc_rates:
  value: [1.0, 0.25, 0.0]

aoc_brackets:
  value: [0, 2000, 4000]
  
aoc_po_thresh_single:
  value: 80000

aoc_po_range_single:
  value: 10000
  
# Share of credit available as refundable credit
aoc_refund_rate:
  value: 0.4
  
llc_rates:
  value: [0.2, 0.0]
  
llc_brackets:
  value: [0, 10000]

llc_po_thresh_single:
  value: 
    '2014': 40000
    '2021': 80000
  i_measure:
    '1986': cpi
    '2017': chained_cpi
    '2020': NA
  i_base_year: 2000
  i_direction: -1
  i_increment: 1000

llc_po_range_single:
  value: 10000
  
