---
indexation_defaults:
  i_measure:
    '1986': cpi
    '2017': chained_cpi
  i_base_year: [1992, 1992, 2012]
  i_direction: [-1, -1, -1]
  i_increment: [50, 50, 50]

filing_status_mapper:
  brackets:
    '1': brackets_single
    '2': brackets_married
    '3': brackets_married / 2
    '4': brackets_head

rates:
  value: [0.0, 0.15, 0.20]

brackets_single:
  value: [0, 22100, 400000]
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: [25, 25, 25]

brackets_married:
  value: [0, 44200, 450000]
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
brackets_head:
  value: [0, 29600, 425000]
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
unrecapture_rate: 
  value: 0.25

collectibles_rate:
  value: 0.28
