#-------------------------------------------------------------------------------
# kg/constants.R -- module overview + declared constants
#
# Capital-gains dynamics behavioral module. Implements the law of motion for
# the policy-induced delta in unrealized capital gains via a representative-
# cell Bellman whose control is the discretionary realization rate r_D
# directly; see other/kg_model_tests/representative_cell_bellman_proposal.md.
#
# Architecture:
#   1. Bathtub pre-pass (kg_dyn_run_bathtub_pass): for each scenario, build an
#      extended age grid [18, A_max_bellman=119] using PerLifeTables mortality
#      past age 80; solve the baseline Bellman once (Pass 1) to recover
#      kappa(a,t), W_B(a,t), MC_B(a,t); then for each year solve the scenario
#      Bellman (Pass 2) to get r_D,S(a,t); apply the bathtub recurrence
#      (survivor + inheritance flows); persist one state file per year per
#      scenario.
#   2. Behavior module (config/scenarios/behavior/kg_dynamics/turnover.R):
#      pure allocator. Reads its year's state file and translates cell-level
#      quantities to per-record kg_lt adjustments via kg_dyn_apply_to_records.
#
# Bellman primitives (ENTROPY realization cost, SINGLE POOL).
# The representative cell maximizes per dollar of unrealized gain:
#   W^j(a,t) = max_{r_D in [0, 1]} {
#       kappa(a,t)*r_D - C(r_D; r_D_B)
#     - tau^j(a,t)*r_D
#     + (1 - r_D) *
#         [beta*(1-m) W^j(a+1,t+1) + beta*m*F^j(a,t)]
#   }
# where r_D_B = clip(r_B, 0, 1) is the cell's baseline discretionary rate: the
# WHOLE baseline realization rate is discretionary, with no r_exog carve-out,
# no responsive/inert split, and no fixed floor. F^j =
# (1 - c_phi^j)*tau^j is the death-state tax-liability forgiveness value
# (c_phi^j is the regime's holder-internalized burden share: 0 step-up, theta
# carryover, 1 deemed). Marginal cost of realization:
#   MC^j(a,t) = tau^j + beta*(1-m)*W^j(a+1,t+1) + beta*m*F^j.
#
# The realization cost is the entropy (KL / Bregman) form anchored at the
# cell's baseline rate r_D_B:
#   C(r_D; r_D_B) = (1/eta) * [ r_D*ln(r_D/r_D_B) - r_D + r_D_B ],
# so C'(r_D) = (1/eta)*ln(r_D/r_D_B) and C'(r_D_B) = 0 exactly.
#   * Pass 1 (baseline inversion): C'(r_D_B) = 0 => kappa = MC^B EXACTLY,
#     interior AND corner.
#   * Pass 2 (scenario FOC): kappa - MC^j = C'(r_D) => the closed form
#       r_D^j = r_D_B * exp(-eta * (MC^j - MC^B)),   clipped to [0, 1].
#     Only the upper clip can bind; r_D_B = 0 cells stay 0. This is a GLOBALLY
#     constant-semi-elasticity response in the structural wedge: dln(r_D)/dMC =
#     -eta everywhere. Since the whole pool responds, eta IS the aggregate
#     long-run semi-elasticity, and the aggregate revenue-maximizing rate is the
#     naive CBO/JCT ~1/eta (no inert floor pushing it out).
#
# The short-run timing margin is a SEPARATE overlay (kg_dyn_build_planned_timing
# + kg_dyn_build_scenario_rate): a calibrated fraction KG_DYN_TIMEABLE_SHARE of
# ALL baseline realizations retimes across the +/-TIMING_WINDOW years, composed
# as r_S = r_ordinary_S + (r_planned_S - r_planned_B). It nets to zero under a
# uniform permanent shock, so it leaves the long-run (level) response untouched.
#
# Current implementation collapses the five tracked wealth classes into a
# single asset bucket; per-asset-class disaggregation is on the roadmap.
#-------------------------------------------------------------------------------



#-------------------------------------------------------------------------------
# Constants
#-------------------------------------------------------------------------------

KG_DYN_AGE_MIN          = 18
KG_DYN_AGE_MAX          = 80      # bathtub topcode (matches simulator)
KG_DYN_AGE_MAX_BELLMAN  = 119     # SSA PerLifeTables hit q(x)=1 at 119

# Fallback annual discount factor for isolated solver unit tests. Production
# paths build a year-varying real-rate series via kg_dyn_load_beta_series
# (tsy_10y Fisher-deflated by year-t YoY CPI-U).
# Value and provenance: config/assumptions/kg.yaml (kg.beta_fallback).

# Realization RESPONSE FORM -- how the scenario-side FOC extrapolates away from
# the calibrated local moment. The entropy Bellman admits two cost primitives
# that fit the SAME local elasticity equally well but extrapolate differently
# (first-order for revenue-maximizing-rate questions); the choice is an
# extrapolation prior, set by the assumption kg.response_form (overridable per
# scenario via the runscript column assumption.kg.response_form):
#   'logs' (DEFAULT) -- constant NET-OF-TAX elasticity (Agersnap-Zidar's
#       preferred spec): log(r_D) is linear in log(1 - MC),
#       r_D = r_D_B * ((1 - MC)/(1 - MC_B))^eta_tilde. Generated by a convex
#       power cost with the same C'(r_D_B) = 0 anchor, so Pass-1 inversion,
#       appliers, tau_eq, and the h/e legs all carry over unchanged. Carries its
#       own independent calibration (eta_tilde AND timeable share). Net-of-tax is
#       the better-motivated extrapolation prior for revenue-maximizing-rate
#       questions and lowers the step-up revmax relative to the semi form.
#   'levels' -- constant SEMI-elasticity: log(r_D) is linear in the structural
#       wedge MC, r_D = r_D_B * exp(-eta*(MC - MC_B)). The joint consequence of a
#       linear payoff + KL/entropy realization cost; eta IS the long-run
#       semi-elasticity.
# Both forms cross at the baseline point by construction (C'(r_D_B) = 0), so the
# baseline pass is form-invariant. Vintages are NOT comparable across forms --
# regenerate before comparing.
kg_dyn_response_form = function() {
  v = economy_param('kg', 'response_form')
  if (!v %in% c('levels', 'logs'))
    stop(sprintf(paste0("kg_dynamics: assumption kg.response_form must be ",
                        "'levels' or 'logs'; got '%s'."), v))
  v
}

# Net-of-tax domain cap: the 'logs' response (1 - MC)^eta_tilde is undefined as
# MC -> 1. Refuse to run (never clamp silently) if any cell's marginal cost MC
# or baseline marginal cost MC_B reaches this. Production MCs sit well below
# (tau ~ 0.238 plus a discounted continuation); a hit signals a broken discount
# series or death-continuation, not a real economy. Levels is unconstrained.
KG_DYN_LOGS_MC_CAP      = 0.98

# Timeable share -- SINGLE POOL. There is no responsive/inert split and no fixed
# floor: the entropy realization cost is a reservation-benefit spectrum
# (exponential b: many easily-deterred dollars, a thin tail of robust sellers)
# that already embeds the "first dollar easier to sell than the last"
# heterogeneity, so a discrete inert carve-out would be a vestige of a
# quadratic (tail-less) cost. Two margins:
#   * LEVEL -- ALL gains respond on the permanent margin via the entropy
#     Bellman (r_D_B = r_B, no r_exog carve-out); eta IS the long-run
#     semi-elasticity directly.
#   * TIMING -- a single calibrated fraction of ALL baseline realizations
#     retimes across the +/-TIMING_WINDOW years (short-run overlay,
#     r_S = r_ordinary_S + (r_planned_S - r_planned_B)).
#
#   KG_DYN_TIMEABLE_SHARE -- fraction of ALL realizations that is mechanically
#       timeable. CALIBRATED against the short-run announcement moment GIVEN eta
#       (the long-run moment pins eta independently: the timing overlay nets to
#       zero under a uniform permanent shock, so long-run is timeable-share
#       invariant). 'NA' forces the unpinned bootstrap -- the finite guard in
#       kg_dyn_run_bathtub_pass hard-stops any sim reaching the Bellman with it
#       unset. Override per scenario via assumption.kg.timeable_share.
#       Value and provenance: config/assumptions/kg.yaml (kg.timeable_share).
# Net-of-tax ('logs') timeable share -- its OWN calibration (the short-run
# announcement moment given eta_tilde), independent of the levels share above.
# kg_dyn_active_timeable_share() surfaces it only when kg.response_form = 'logs'.
# The timing overlay is a mechanical fraction, not a Bellman response, so it is
# nearly form-robust; the long-run moment is timeable-invariant, so eta_tilde and
# this share identify sequentially. Override via assumption.kg.timeable_share_logs.
# Value and provenance: config/assumptions/kg.yaml (kg.timeable_share_logs).

# Applier-only deemed-realization avoidance haircut: a data-calibration
# parameter (valuation games / noncompliance that JCT and Treasury assume but
# the Bellman doesn't), NOT tax law. Scales the per-record deemed contribution
# by (1 - KG_DYN_DEEMED_AVOIDANCE) in kg_dyn_apply_to_records; does NOT enter
# c_phi (lifetime realization still sees the full deemed burden). Set to 0 for
# no haircut.
# Default 0.25 (a 25% value discount), consistent with the estate-side
# pass-through discount (rho_pt ~ 0.65).
# TODO: this is the same object as the estate-tax asset-class reporting factor
# (a valuation discount on closely-held/illiquid assets) -- concord the two on a
# shared per-asset-class rho_k.
# Value and provenance: config/assumptions/kg.yaml (kg.deemed_avoidance).

# Fraction of planned dollars that move toward the best year in the window
# is clamp((tau_S - tau_B between source and destination) / ref_wedge, 0, 1).
# 5pp moves the full bucket; 1pp moves 20%. tau_S here is the LAW-ONLY tau
# (mtr_kg_lt_lawonly: reform MTRs on the pre-mech-injection frame), so the
# wedge is exactly zero when the living-side schedule is unchanged --
# post-injection MTRs would drift a few bp from the income effect of
# mechanically-routed carryover realizations and retime against noise.
# Value and provenance: config/assumptions/kg.yaml (kg.timing_ref_wedge).

# Static resource: dollar-weighted heir-age distribution derived from SCF
# 2022 inheritance data (filtered to non-gift transfers, weighted by
# Gale-Sabelhaus 2024 recency probabilities for the current-year flow).
# Built by other/kg_model_tests/build_heir_distribution.R; see that script
# for the filter definitions. Treated as a model constant because the
# upstream survey is not year-varying at the projection horizons we use.
KG_DYN_HEIR_DISTRIBUTION_PATH = './resources/heir_distribution_scf2022.csv'

# eta -- the entropy-cost precision. In the SINGLE POOL eta IS the long-run CG
# semi-elasticity directly (the Bellman responds on the whole pool, so there is
# no responsive-half deflation). Pinned on the FULL SIMULATOR, not internally:
# the eta_dial grid measures E_full(eta) = dlog(R)/dtau at sim-year 30 across a
# few eta values and inverts the (linear-through-origin) line for
# eta* = |E_full_target| / slope, with E_full_target = -0.6 / 0.238 = -2.52
# (literature realization elasticity at the top-rate divisor). Protocol and the
# fitted grid: other/top_tax/eta_dial/ (measure_efull_by_eta.R,
# eta_repin_fit.csv), so a re-pin is arithmetic. The timeable share is calibrated
# against the short-run announcement moment GIVEN this eta. Response is
# INCREASING in |eta|. Re-pin whenever Tax-Data vintage, the timeable share,
# ref_wedge, the discount series, the apply-to-records logic, or any Bellman
# primitive changes -- the provenance guard below flags a mismatch.
#
# 'NA' forces the unpinned bootstrap: the finite-eta guard in
# kg_dyn_run_bathtub_pass hard-stops any sim that reaches the Bellman with eta
# unset (intended -- prevents accidental sims on an uncalibrated model).
# Value and provenance: config/assumptions/kg.yaml (kg.eta).

# eta_tilde -- the NET-OF-TAX ('logs') cost precision. Under the power cost it
# is the constant net-of-tax elasticity dlog(r_D)/dlog(1 - MC) = eta_tilde.
# Pinned on the full simulator by the SAME protocol and against the SAME local
# moment as the levels eta; grid + fit in
# other/kg_model_tests/form_ab/eta_tilde_fit.csv. Lower than the levels eta
# because the net-of-tax full-sim slope is steeper, so the same E_full needs a
# smaller eta_tilde. Override via assumption.kg.eta_logs ('NA' forces the
# unpinned bootstrap hard-stop).
# Value and provenance: config/assumptions/kg.yaml (kg.eta_logs).

# Active-form resolvers: the single place that maps the response form to that
# form's calibrated pair. Consumed by kg_dyn_run_bathtub_pass (arg defaults) and
# kg_dyn_build_planned_timing so every downstream consumer sees the right form's
# values without threading the form name everywhere. A YAML value of the string
# 'NA' forces the unpinned bootstrap, which the finite guard in
# kg_dyn_run_bathtub_pass then hard-stops on -- deliberate, so an uncalibrated
# model cannot be simulated by accident.
kg_dyn_as_pinned = function(v) {
  if (identical(as.character(v), 'NA')) NA_real_ else as.numeric(v)
}
kg_dyn_active_eta = function(form = kg_dyn_response_form()) {
  kg_dyn_as_pinned(
    if (identical(form, 'logs')) economy_param('kg', 'eta_logs')
    else                         economy_param('kg', 'eta'))
}
kg_dyn_active_timeable_share = function(form = kg_dyn_response_form()) {
  kg_dyn_as_pinned(
    if (identical(form, 'logs')) economy_param('kg', 'timeable_share_logs')
    else                         economy_param('kg', 'timeable_share'))
}

# Within-cell allocation rule for policy-induced dG, controlling the
# effective cell mortality m_eff used in the death/survivor channels.
#   "G" — dG allocated proportional to G_unit; m_eff = sum(w*m*G)/sum(w*G).
#         Inheritance-flow story.
#   "R" — dG allocated proportional to positive kg_lt; m_eff = sum(w*m*R)/sum(w*R).
#         Lock-in story. Falls back to "G" when R_B = 0.
# Only affects carryover/deemed; step-up is unchanged (death channel off).
# Value and provenance: config/assumptions/kg.yaml (kg.dg_allocation).

# Within-cell allocation rule used by the per-record APPLIER to distribute the
# lock-in/carryover stock realization (extra_R) across records in an age cell.
#   "R" (= 0)  — proportional to positive kg_lt (falls back to G_unit share
#                when R_B = 0). Historical behavior: targets active realizers
#                (trading-propensity proxy).
#   "G" (= 1)  — proportional to G_unit (falls back to kg_lt share when
#                G_B = 0). Holdings-based: targets holders of unrealized
#                gains.
#   numeric a in [0, 1] — convex blend: (1-a)*R_share + a*G_share. The
#                realized carryover dollar needs a holder (G) who sells (R);
#                a blend is the reduced-form compromise between the proxies.
# Note the recurrence's death-channel m_eff stays on KG_DYN_DG_ALLOCATION
# ('G') regardless: whose dollars DIE follows holdings; whose dollars get
# SOLD is what this knob controls. Overridable per scenario via the runscript
# column assumption.kg.applier_allocation for comparison runs.
#
# Default 0.5: the realized carryover dollar requires a holder who sells, so
# neither proxy alone is right. Carryover mechanical revenue is monotone in this
# knob (R gives the most, G the least); deemed is invariant to it.
# NOTE: the Bellman calibration (eta/timeable_share) is conditioned on this 0.5
# default -- re-pin if it changes.
# Value and provenance: config/assumptions/kg.yaml (kg.applier_allocation).

KG_DYN_ASSET_CLASSES    = c('equities', 'pass_throughs',
                            'primary_home', 'other_home', 're_fund')
KG_DYN_ASSET_VALUE_COLS = paste0('value.', KG_DYN_ASSET_CLASSES)
KG_DYN_ASSET_BASIS_COLS = paste0('basis.', KG_DYN_ASSET_CLASSES)
KG_DYN_ASSET_GAIN_COLS  = paste0('gain.',  KG_DYN_ASSET_CLASSES)

# Estate gross-asset value columns: the canonical list is ESTATE_ASSET_COLS
# (src/calc/functions/tax/estate.R), which wealth_dynamics.R also consumes.
# kg references it directly so the three channels stay in lockstep on what
# counts as a gross-estate asset.

# Terminal-charity logit coefficients on log(gross estate, 2026 $M) and the
# deflation base year: config/assumptions/kg.yaml (kg.char_*). NOTE: no source
# for the four fitted coefficients is recorded anywhere in the repository --
# flagged in the config for the author to fill in.

# Trustees Report Alternative 2, 50/50 male/female blend (cohort module is
# gender-blind). Supplies the 81+ tail of the Bellman extended grid.
KG_DYN_LIFE_TABLE_M_PATH = './resources/PerLifeTables_M_Alt2_TR2024.csv'
KG_DYN_LIFE_TABLE_F_PATH = './resources/PerLifeTables_F_Alt2_TR2024.csv'


# Per-asset death-regime codes. The YAML carries one
# pref.kg_death_regime_{class} per asset class; kg_dyn_build_regime_mix
# resolves them at the cell level via gain-stock-weighted averaging.
# c_phi(a,t) (death-state burden share the holder internalizes) is the
# share of cell gain stock taxed at death given the regime mix, theta on
# carryover-routed shares, and the cell-level §121 utilization aggregate
# G_B_primary_above_cap / G_B_primary on primary_home dollars.
KG_DYN_REGIME_TRIPLET = list(
  '0' = list(vanish = 1, route = 0, realize = 0),  # step_up
  '1' = list(vanish = 0, route = 1, realize = 0),  # carryover
  '2' = list(vanish = 0, route = 0, realize = 1)   # deemed_realization
)



#-------------------------------------------------------------------------------
# Calibration provenance + staleness guard
#
# SUPERSEDED by the model-wide assumptions layer (src/misc/assumptions.R).
# eta/timeable_share are valid only for the conditions they were calibrated
# under -- Tax-Data vintage, ref_wedge, discount series, apply-to-records logic,
# Bellman primitives. Left in comments alone those dependencies go unnoticed: an
# applier-rule change once biased every conventional kg estimate by ~37% on a
# 5pp gains-rate score before it was caught.
#
# Those dependencies now live in config/assumptions/kg.yaml as each calibrated
# entry's derived_under (data vintages) and invalidated_by (code files, checked
# by content hash), and config_check_staleness() HARD STOPS the run rather
# than warning. The old warn-only stamp and its KG_STRICT_CALIB escape hatch are
# gone; a deliberate sweep now overrides the value in the runscript, which
# records the choice in the vintage's assumptions.csv.
#-------------------------------------------------------------------------------

# Bump whenever the Bellman primitives, pool structure, or apply-to-records
# logic change in a way that invalidates eta/timeable_share. Carried on every
# kg state file so a bathtub state written under one spec is never consumed
# under another.
# Do NOT bump for a change that provably reproduces the calibration conditions
# (the wealth-tax carrying cost, for instance: h == 0 under tau_w = 0, so the
# calibration stands and a bump would only make the guard cry wolf every run).
KG_DYN_SPEC_VERSION = 3L

#-------------------------------------------------------------------------------
# Three-bucket realization timing helpers
#-------------------------------------------------------------------------------

kg_dyn_validate_timing_params = function(
    timeable_share = kg_dyn_active_timeable_share(),
    timing_window  = economy_param('kg', 'timing_window'),
    ref_wedge      = economy_param('kg', 'timing_ref_wedge')) {

  # Single-pool (spec v3) timing parameters. timeable_share is the fraction of
  # ALL realizations that retimes across the window. NA is permitted here
  # (uncalibrated) and hard-stopped later in kg_dyn_run_bathtub_pass -- so the
  # source-time self-call below validates only structure. A non-NA share must be
  # a finite scalar in [0, 1].
  if (!is.na(timeable_share) &&
      (length(timeable_share) != 1 || !is.finite(timeable_share) ||
       timeable_share < 0 || timeable_share > 1)) {
    stop(sprintf(paste0('kg_dynamics: assumption kg.timeable_share must be a ',
                        'finite scalar in [0, 1] (or NA when uncalibrated); got %s.'),
                 paste(format(timeable_share), collapse = ', ')))
  }
  if (length(timing_window) != 1 || is.na(timing_window) ||
      timing_window < 0 || timing_window != as.integer(timing_window)) {
    stop('kg_dynamics: assumption kg.timing_window must be a nonnegative integer.')
  }
  if (length(ref_wedge) != 1 || !is.finite(ref_wedge) || ref_wedge <= 0) {
    stop('kg_dynamics: assumption kg.timing_ref_wedge must be a positive finite number.')
  }

  invisible(TRUE)
}

# NOTE: no source-time self-call. Assumptions are scenario-scoped and are not
# active when this file is sourced; kg_dyn_run_bathtub_pass validates instead.



