---

# Whether SSN is required to qualify for CTC
need_ssn:
  value:
    '2014': 0
    '2018': 1
    '2021': 0
    '2022': 1
    '2026': 0

# Maximum age to qualify as an "old" child
old_age_limit:
  value:
    '2014': 16
    '2021': 17
    '2022': 16
    '2026': 17

# Maximum credit value per "young" child
value_young:
  value: 
    '2014': [1000, 0]
    '2018': [2000, 0]
    '2021': [2000, 1600]
    '2022': [2000, 0]
    '2026': [3600, 0]

# Maximum credit value per "old" child
value_old:
  value:
    '2014': [1000, 0]
    '2018': [2000, 0]
    '2021': [2000, 1000]
    '2022': [2000, 0]
    '2026': [3000, 0] 
