---
    
# Maximum amount of auto loan interest deductible from gross income
auto_int_ded_limit:
  value:
    '2014': 0
    '2025': 10000
    '2029': 0

# Threshold above which auto loan interest deduction begins to phase out, non-joint returns
auto_int_ded_po_thresh_single:
  value:
    '2014': Inf
    '2025': 100000
    '2029': Inf

# Phaseout rate for auto loan interest deduction 
auto_int_ded_po_rate:
  value:
    '2014': 0
    '2025': 0.2
    '2029': 0
