---
# Whether phase-in type is a rate (0 means range)
pi_type:
  value:
    '2014': 1
    '2023': 0
    '2026': 1

  
# Phase-in range
pi_range: 
  value: 
    '2014': Inf
    '2023': 12000
    '2024': 12666
    '2025': 13333
    '2026': Inf
