---
indexation_defaults:
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year:
    '2019': 2017
    '2026': 1987
  i_direction: -1
  i_increment: 100

filing_status_mapper:
  value:
    '1': value_single
    '2': value_single * 2
    '3': value_single
    '4': value_single
  po_thresh:
    '1': po_thresh_single
    '2': po_thresh_single * 2
    '3': po_thresh_single
    '4': po_thresh_single * 1.5
  brackets:
    '1': brackets_single
    '2': brackets_single * 2
    '3': brackets_single
    '4': brackets_single * 1.2
  need_ssn:
    '1': need_ssn_single
    '2': need_ssn_married
    '3': need_ssn_single
    '4': need_ssn_single

value_single:
  value:
    '2019': 12000
    '2026': 3000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

po_thresh_single:
  value: 200000

brackets_single:
  value:
    '2019': [0, 25000, 50000]
    '2021': [0]
    '2023': [0, 25000, 50000]
  i_measure: default
  i_base_year:
    '2019': [2018, 2018, 2018]
    '2021': [2020]
    '2023': [2018, 2018, 2018]
  i_direction:
    '2019': [1, 1, 1]
    '2021': [0]
    '2023': [1, 1, 1]
  i_increment:
    '2019': [50, 50, 100]
    '2021': [10]
    '2023': [100, 100, 100]

need_ssn_single:
  value:
    '2019': False
    '2021': True

need_ssn_married:
  value: False
