---

# Maximum deductible state and local taxes, joint returns
salt_limit_married:
  value:
    '2014': Inf
    '2018': 10000

# Years after which mortgage interest deduction is limited based on mortgage balance. Maps to mort_bal_limit 
mort_bal_limit_years:
  value: 
    '2014': [1987, Inf]
    '2018': [1987, 2017, Inf]

# Limitations on deductible mortgage interest based on mortgage balance, single filers
mort_bal_limit_single:
  value:
    '2014': [Inf, 1000000]
    '2018': [Inf, 1000000, 750000]

# Limitations on deductible mortgage interest based on mortgage balance, joint filers
mort_bal_limit_married:
  value:
    '2014': [Inf, 1000000]
    '2018': [Inf, 1000000, 750000]

# Limitations on deductible mortgage interest based on mortgage balance, married filing separately filers
mort_bal_limit_mfs:
  value:
    '2014': [Inf, 500000]
    '2018': [Inf, 500000, 375000]

# Maximum deductible "miscellanous" itemized deductions
misc_limit:
  value:
    '2014': Inf
    '2018': 0

# Maximum deductible casualty and loss expenses
casualty_limit:
  value: 
    '2014': Inf
    '2018': 0
    
# AGI threshold above which itemized deductions are limited under Pease, single filers
pease_thresh_single:
  value:
    '2014': 250000
    '2018': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# AGI threshold above which itemized deductions are limited under Pease, joint filers  
pease_thresh_married:
  value:
    '2014': 300000
    '2018': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default  
 
# AGI threshold above which itemized deductions are limited under Pease, head-of-household filers
pease_thresh_head:
  value:
    '2014': 275000
    '2018': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
# Tax value limitation reduction threshold, nonjoint returns (i.e. next bracket where rate corresponding to maximum tax value ends)
limit_tax_value_thresh_single:
  value:
    '2014': Inf
    '2026': 500000
  i_measure: default
  i_base_year:
    '2014': NA
    '2026': 2017
  i_direction: -1
  i_increment: 25
    
# Tax value limitation reduction threshold, joint returns (i.e. next bracket where rate corresponding to maximum tax value ends)
limit_tax_value_thresh_married:
  value:
    '2014': Inf
    '2026': 600000
  i_measure: default
  i_base_year:
    '2014': NA
    '2026': 2017
  i_direction: -1
  i_increment: 50
  
# Tax value limitation reduction rate, non-SALT (i.e. percentage point diference between maximum statutory tax value and target value) 
limit_tax_value_rate:
  value:
    '2014': 0
    '2026': 0.05405405
