---
indexation_defaults:
  i_measure:
    '1986': cpi
    '2017': chained_cpi
  i_base_year:
    '2014': 2017
  i_direction: 0
  i_increment: 1000

filing_status_mapper:
  kg_loss_limit:
    '1': kg_loss_limit_married
    '2': kg_loss_limit_married
    '3': kg_loss_limit_married / 2
    '4': kg_loss_limit_married
  bus_loss_limit:
    '1': bus_loss_limit_married / 2
    '2': bus_loss_limit_married
    '3': bus_loss_limit_married / 2
    '4': bus_loss_limit_married / 2
  sl_limit:
    '1': sl_limit_single
    '2': sl_limit_single
    '3': sl_limit_single * 0
    '4': sl_limit_single
  sl_po_thresh:
    '1': sl_po_thresh_single
    '2': sl_po_thresh_married
    '3': sl_po_thresh_single
    '4': sl_po_thresh_single
  sl_po_range:
    '1': sl_po_range_single
    '2': sl_po_range_single * 2
    '3': sl_po_range_single
    '4': sl_po_range_single
  auto_int_ded_po_thresh:
    '1': auto_int_ded_po_thresh_single
    '2': auto_int_ded_po_thresh_single * 2
    '3': auto_int_ded_po_thresh_single
    '4': auto_int_ded_po_thresh_single

# Maxmimum deductible capital loss, joint returns
kg_loss_limit_married:
  value: 3000
  
  # Share of capital gains excluded from AGI
kg_excl_rate:
  value: 0
  
# Share of (current-law-taxable) interest income excluded from AGI
int_excl_rate:
  value: 0
  
# Share of (current-law-taxable) div excluded from AGI
div_excl_rate:
  value: 0

# Maximum deductible business loss
bus_loss_limit_married:
  value:
    '2014': Inf
    '2022': 500000
    '2029': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
# Year during and after which a divorce does not generate taxable/deductible alimony
alimony_repeal_year:
  value: 
    '2014': Inf
    '2018': 2018
    '2025': Inf

# Maximum deductible student loan interest
sl_limit_single:
  value: 2500

# MAGI phaseout threshold for student loan interest deduction, single filers
sl_po_thresh_single:
  value: 50000
  i_measure: default
  i_base_year: 2001
  i_direction: -1
  i_increment: 5000
  
# MAGI phaseout threshold for student loan interest deduction, joint returns
sl_po_thresh_married:
  value: 100000
  i_measure: default
  i_base_year: 2001
  i_direction: -1
  i_increment: 5000

# MAGI phaseout range for student loan interest deduction
sl_po_range_single:
  value: 15000
  
# Maximum tuition and fees deduction
tuition_ded_limit:
  value: 
    '2014': Inf
    '2021': 0
    
# Maximum domestic production activities deduction
dpad_limit:
  value:
    '2014': Inf
    '2018': 0
    
# Maximum amount of auto loan interest deductible from gross income
auto_int_ded_limit:
  value:
    '2014': 0

# Threshold above which auto loan interest deduction begins to phase out, non-joint returns
auto_int_ded_po_thresh_single:
  value:
    '2014': Inf

# Phaseout rate for auto loan interest deduction 
auto_int_ded_po_rate:
  value: 0