---
indexation_defaults:
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year: 2025
  i_direction: -1
  i_increment: 100

filing_status_mapper:
  po_thresh:
    '1': po_thresh_single
    '2': po_thresh_single * 2
    '3': po_thresh_single
    '4': po_thresh_single

# Minimum amount of caregiving expenses above which credit phases in    
exp_floor:
  value: 2000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# Minimum amount of earned income to qualify
min_ei:
  value: 7500
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# Credit rate (share of eligible expenses)
credit_rate:
  value: 0

# Maximum credit value
max_credit:
  value: 5000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# AGI threshold above which credit begins phasing out, non-joint returns
po_thresh_single:
  value: 75000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
    
# Rate at which credit phases out with AGI    
po_rate:
  value: 0.1

# Whether credit is refundable
refundable:
  value: 0 
