---

filing_status_mapper:
  young_po_thresh:
    '1': young_po_thresh
    '2': young_po_thresh
    '3': young_po_thresh
    '4': young_po_thresh
  old_po_thresh:
    '1': old_po_thresh
    '2': old_po_thresh
    '3': old_po_thresh
    '4': old_po_thresh
  young_po_rate:
    '1': young_po_rate
    '2': young_po_rate
    '3': young_po_rate
    '4': young_po_rate
  old_po_rate:
    '1': old_po_rate
    '2': old_po_rate
    '3': old_po_rate
    '4': old_po_rate
    
# Maximum credit-eligible expenses per qualifying dependent 
exp_limit:
  value: 
    '2014': 3000
    '2021': 8000
    '2022': 3000

# Maximum number of qualifying dependents 
n_dep_limit:
  value: 2

# Maximum age to be considered a young qualifying dependent
young_age_limit:
  value: 4
  
# Maximum age to be considered an old qualifying dependent
old_age_limit:
  value: 12

# Young dependents: credit rates 
young_rate:
  value:
    '2014': [0.2, 0.15, 0.0]
    '2021': [0.2, 0.3, 0.0]
    '2022': [0.2, 0.15, 0.0]
  
# Young dependents: AGI threshold above which credit rate begins phasing out from max to min
young_po_thresh:
  value:
    '2014': [Inf, 15000, 0]
    '2021': [400000, 125000, 0]
    '2022': [Inf, 15000, 0]

# Young dependents: rate at which credit rate phases out with AGI
young_po_rate:
  value: 
    '2014': [0.0, 0.000005, 0.0]
    '2021': [0.000005, 0.000005, 0.0]
    '2022': [0.0, 0.000005, 0.0]
    
# Old dependents: credit rates 
old_rate:
  value:
    '2014': [0.2, 0.15, 0.0]
    '2021': [0.2, 0.3, 0.0]
    '2022': [0.2, 0.15, 0.0]
  
# Old dependents: AGI threshold above which credit rate begins phasing out from max to min
old_po_thresh:
  value:
    '2014': [Inf, 15000, 0]
    '2021': [400000, 125000, 0]
    '2022': [Inf, 15000, 0]

# Old dependents: rate at which credit rate phases out with AGI
old_po_rate:
  value: 
    '2014': [0.0, 0.000005, 0.0]
    '2021': [0.000005, 0.000005, 0.0]
    '2022': [0.0, 0.000005, 0.0]

# Rounding step for descretized phaseout function
discrete_step:
  value: 2000

# Whether credit is refundable
refundable:
  value:
    '2014': 0
    '2021': 1
    '2022': 0
