---
indexation_defaults:
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year: 1995
  i_direction: 0
  i_increment: 10

filing_status_mapper:
  po_thresh_0:
    '1': po_thresh_0
    '2': po_thresh_0 + po_thresh_marriage_adj
    '3': po_thresh_0
    '4': po_thresh_0
  po_thresh_1:
    '1': po_thresh_1
    '2': po_thresh_1 + po_thresh_marriage_adj
    '3': po_thresh_1
    '4': po_thresh_1
  po_thresh_2:
    '1': po_thresh_2
    '2': po_thresh_2 + po_thresh_marriage_adj
    '3': po_thresh_2
    '4': po_thresh_2
  po_thresh_3:
    '1': po_thresh_3
    '2': po_thresh_3 + po_thresh_marriage_adj
    '3': po_thresh_3
    '4': po_thresh_3

# Credit phase-in rate for filers with no qualifying children 
pi_rate_0:
  value: 
    '2014': 0.0765
    '2021': 0.153
    '2022': 0.0765

# Credit phase-in rate for filers with 1 child  
pi_rate_1:
  value: 0.34

# Credit phase-in rate for filers with 2 children
pi_rate_2:
  value: 0.4

# Credit phase-in rate for filers with 3+ children  
pi_rate_3:
  value: 0.45

# Credit phase-out rate for filers with no children  
po_rate_0:
  value: 0.0765

# Credit phase-out rate for filers with 1 child  
po_rate_1:
  value: 0.1598
  
# Credit phase-out rate for filers with 2 children  
po_rate_2:
  value: 0.2106

# Credit phase-out rate for filers with 3+ children  
po_rate_3:
  value: 0.2106

# Earned income threshold at which credit is maximized for filers with no children 
pi_end_0:
  value:
    '2014': 4220
    '2021': 9820
    '2022': 4220
  i_measure: default
  i_base_year:
    '2014': 1995
    '2021': 2020
    '2022': 1995
  i_direction: default
  i_increment: default

# Earned income threshold at which credit is maximized for filers with 1 child 
pi_end_1:
  value: 6330
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# Earned income threshold at which credit is maximized for filers with 2 children 
pi_end_2:
  value: 8890
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# Earned income threshold at which credit is maximized for filers with 3+ children 
pi_end_3:
  value: 8890
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# AGI threshold at which credit begins phasing out for filers with no children
po_thresh_0:
  value: 
    '2014': 5280
    '2021': 11610
    '2022': 5280
  i_measure: 
  i_base_year:
    '2014': 1995
    '2021': 2020
    '2022': 1995
  i_direction: default
  i_increment: default

# AGI threshold at which credit begins phasing out for filers with 1 child
po_thresh_1:
  value: 11610
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# AGI threshold at which credit begins phasing out for filers with 2 children
po_thresh_2:
  value: 11610
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# AGI threshold at which credit begins phasing out for filers with 3 children
po_thresh_3:
  value: 11610
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# Phaseout threshold add-factor for joint returns
po_thresh_marriage_adj:
  value: 5000
  i_measure: default
  i_base_year: 2008
  i_direction: default
  i_increment: default

# Maximim allowable investment income for credit eligibility
inv_inc_limit:
  value: 
    '2014': 2200
    '2021': 10000
  i_measure: default
  i_base_year: 
    '2014': 1995
    '2021': 2020
  i_direction: -1
  i_increment: 50

# Minimum age for credit eligibility
min_age:
  value: 
    '2014': 25
    '2021': 19
    '2022': 25

# Maximum age for credit eligibility
max_age:
  value:
    '2014': 64
    '2021': Inf
    '2022': 64
    
# Whether credit is available for married filing separately returns   
mfs_eligible:
  value: 0

# Whether parents are required to pre-certify their eligibility
parent_precert:
  value: 0
