---
indexation_defaults:
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year:
    '2014': 2012
  i_direction: -1
  i_increment: 50

filing_status_mapper:
  po_thresh:
    '1': po_thresh_single
    '2': po_thresh_married
    '3': po_thresh_married / 2
    '4': po_thresh_head
  po_range:
    '1': po_range_single
    '2': po_range_single
    '3': po_range_single / 2
    '4': po_range_single

# Personal exemption value
value:
  value:
    '2014': 2000
    '2018': 0
    '2026': 2000
  i_measure:
    '1986': cpi
    '2017': chained_cpi
  i_base_year: 1988
  i_direction: -1
  i_increment: 50

# Phaseout threshold, single filers
po_thresh_single:
  value:
    '2014': 250000
    '2018': Inf
    '2026': 250000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# Phaseout threshold, joint filers  
po_thresh_married:
  value:
    '2014': 300000
    '2018': Inf
    '2026': 300000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default  
 
# Phaseout threshold, head-of-household filers
po_thresh_head:
  value:
    '2014': 275000
    '2018': Inf
    '2026': 275000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# Phaseout range, single
po_range_single:
  value: 125000

# Whether phaseout is discretized, as per pre-TCJA law
po_discrete:
  value: 1
  
# Rounding step for discretized phaseout
po_discrete_step:
  value: 0.02
