---
indexation_defaults:
  i_measure:
    '2022': awi
  i_base_year: [2022, 2022]
  i_direction: [1, 1]
  i_increment: [300, 300]

filing_status_mapper:
  add_med_brackets:
    '1': add_med_brackets_single
    '2': add_med_brackets_married
    '3': add_med_brackets_married / 2
    '4': add_med_brackets_single

# Whether tips are exempt from payroll tax
tips_exempt:
  value: 0

# Share of self-employment earnings subject to SECA tax. See code for 
# explanation of why this is a separate parameter from sum of payroll tax rates
seca_taxable_rate:
  value: 0.9235
  
# Threshold above which total self-employment income must be reported
se_thresh:
  value: 400

# OASDI rates, employee side 
oasdi_ee_rates:
  value: [0.062, 0.0]
  
# OASDI brackets, employee side 
oasdi_ee_brackets:
  value: 
    '2014': [0, 117000]
    '2015': [0, 118500]
    '2016': [0, 118500]
    '2017': [0, 127200]
    '2018': [0, 128400]
    '2019': [0, 132900]
    '2020': [0, 137700]
    '2021': [0, 142800]
    '2022': [0, 147000]
    '2023': [0, 160200]
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# OASDI rates, employer side 
oasdi_er_rates:
  value: [0.062, 0.0]
  
# OASDI brackets, employer side 
oasdi_er_brackets:
  value: 
    '2014': [0, 117000]
    '2015': [0, 118500]
    '2016': [0, 118500]
    '2017': [0, 127200]
    '2018': [0, 128400]
    '2019': [0, 132900]
    '2020': [0, 137700]
    '2021': [0, 142800]
    '2022': [0, 147000]
    '2023': [0, 160200]
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
# Hospital Insurance rates, employee side 
hi_ee_rates:
  value: 0.0145

# Hospital Insurance brackets, employee side
hi_ee_brackets:
  value: 0
  
# Hospital Insurance rates, employer side 
hi_er_rates:
  value: 0.0145
  
# Hospital Insurance brackets, employer side
hi_er_brackets:
  value: 0

# Additional Medicare Tax rates
add_med_rates:
  value: [0.0, 0.009]

# Additional Medicare Tax brackets for single filers
add_med_brackets_single:
  value: [0, 200000]

# Additional Medicare Tax brackets for joint filers
add_med_brackets_married:
  value: [0, 250000]
