---
indexation_defaults:
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year: 2017
  i_direction: -1
  i_increment: 50

filing_status_mapper:
  po_thresh_sstb:
    '1': po_thresh_sstb_single
    '2': po_thresh_sstb_single * 2
    '3': po_thresh_sstb_single
    '4': po_thresh_sstb_single
  po_thresh_non_sstb:
    '1': po_thresh_non_sstb_single
    '2': po_thresh_non_sstb_single * 2
    '3': po_thresh_non_sstb_single
    '4': po_thresh_non_sstb_single
  po_range_sstb:
    '1': po_range_sstb_single
    '2': po_range_sstb_single * 2
    '3': po_range_sstb_single
    '4': po_range_sstb_single
  po_range_non_sstb:
    '1': po_range_non_sstb_single
    '2': po_range_non_sstb_single * 2
    '3': po_range_non_sstb_single
    '4': po_range_non_sstb_single

# Deduction rate
rate:
  value: 
    '2014': 0.0
    '2018': 0.2
    '2026': 0.0
  
# Taxable income phaseout threshold for SSTBs, single filers
po_thresh_sstb_single:
  value: 157500
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# Taxable income phaseout threshold for non-SSTBs, single filers
po_thresh_non_sstb_single:
  value: 157500
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# Taxable income phaseout range for SSTBs, single filers
po_range_sstb_single:
  value: 50000
  
# Taxable income phaseout range for non-SSTBs, single filers
po_range_non_sstb_single:
  value: 50000

# For SSTBs, whether paying wages excepts taxpayer from taxable income phaseout  
wage_exception_sstb:
  value: 0

# For non-SSTBs, whether paying wages excepts taxpayer from taxable income phaseout 
wage_exception_non_sstb:
  value: 1

# Share of W2 wage bill required for full deduction after phase-out 
wage_limit:
  value: 0.5
  
# Share of ordinary taxable income limit
txbl_inc_limit:
  value: 0.2

# Whether QBI deduction doesn't have a set phase out
no_po:
  value: 0

