---
indexation_defaults:
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year: 2017
  i_direction: -1
  i_increment: 50

filing_status_mapper:
  po_thresh:
    '1': po_thresh_single
    '2': po_thresh_single * 2
    '3': po_thresh_single
    '4': po_thresh_single
  po_range:
    '1': po_range_single
    '2': po_range_single * 2
    '3': po_range_single
    '4': po_range_single

# Deduction rate
rate:
  value: 
    '2014': 0.0
    '2018': 0.2
    '2026': 0.0
  
# Taxable income phaseout threshold, single filers
po_thresh_single:
  value: 157500
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# Taxable income phaseout range, single filers
po_range_single:
  value: 50000
  
# Share of W2 wage bill required for full deduction after phase-out 
wage_rate:
  value: 0.5


