---
indexation_defaults:
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year:
    '2014': 1987
    '2018': 2017
    '2026': 1987
  i_direction: -1
  i_increment: 50

filing_status_mapper:
  value:
    '1': value_single
    '2': value_single * 2
    '3': value_single
    '4': value_head
  bonus:
    '1': bonus_single
    '2': bonus_married
    '3': bonus_single
    '4': bonus_single
  bonus_other:
    '1': bonus_other
    '2': bonus_other * 2
    '3': bonus_other
    '4': bonus_other * 1.5
  bonus_elderly_temp_thresh:
    '1': bonus_elderly_temp_thresh
    '2': bonus_elderly_temp_thresh * 2
    '3': bonus_elderly_temp_thresh
    '4': bonus_elderly_temp_thresh

# Base value for single filers
value_single:
  value:
    '2014': 3000
    '2018': 12000
    '2026': 3000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
# Base value for HOH filers
value_head:
  value:
    '2014': 4400
    '2018': 18000
    '2026': 4400
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# Elderly/blind bonus for single filers
bonus_single:
  value: 750
  i_measure: default
  i_base_year: 1987
  i_direction: default
  i_increment: default

# Elderly/blind bonus for joint filers  
bonus_married:
  value: 600
  i_measure: default
  i_base_year: 1987
  i_direction: default
  i_increment: default
  
# Minimum standard deduction for dependent returns
dep_floor:
  value: 500
  i_measure: default
  i_base_year: 1987
  i_direction: default
  i_increment: default
  
# Amount of bonus deduction added to earned income for dependent returns 
dep_earned_bonus:
  value: 250
  i_measure: default
  i_base_year: 1997
  i_direction: default
  i_increment: default

# Additional other bonus
bonus_other:
  value: 
    '2014': 0

# Elderly temporary bonus
bonus_elderly_temp_value:
  value: 0

# Phasehout threshold of elderly temp bonus
bonus_elderly_temp_thresh:
  value: 75000

