---
indexation_defaults:
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year: 2025
  i_direction: -1
  i_increment: 1000

filing_status_mapper:
  threshold:
    '1': threshold_single * 1
    '2': threshold_single * 2
    '3': threshold_single * 1
    '4': threshold_single * 1

# Threshold above which the AGI surtax applies
threshold_single:
  value:
    '2014': 1000000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# Surtax rate applied to income exceeding the threshold
rate:
  value: 0.0  
