---
title: "Data Processing and Population Projections"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This section describes how we clean, augment, and project the underlying tax data. The code which implements these calculations and algorithms can be found in the [Tax-Data](https://github.com/Budget-Lab-Yale/Tax-Data) repository.

## IRS PUF
The basis of the tax model is a representative and anonymized sample of tax returns purchased from the IRS. This public-use file, or “PUF”, contains more than 150,000 records (about a 1 percent sample of returns) with information on most variables required to calculate taxes: filing status, number of dependents, income composition, deductions, and more. The IRS also offers a supplemental file with additional demographic information, like age and gender, for a subset of taxpayers. However, for our purposes, the PUF has two major shortcomings:

- **Timing.** For a specific tax year, the PUF only becomes available many years later. For example, as of early 2024, the most recently available PUF is for tax year 2015. This lag means that the underlying data is out of date. Major statistical adjustments are required to “age” the PUF forward to reflect population characteristics of a more recent tax year – our jump-off point for making projections into the future.

- **Limited Universe** By definition, the PUF is limited to the tax-filing universe. But our work requires knowing the characteristics of the non-filing population, who may be affected by counterfactual policy reforms. We also encounter truncation and censoring issues for some variables. For example, we do not observe donations for those who do not elect to itemize deductions. To overcome these limitations, we build statistical models to impute these records and attributes.

Note that our choice to use the PUF (a data source that cannot be exposed to unauthorized users) as our core dataset means that we cannot offer the model as a fully open-source project. One potential alternative approach would be to begin with a publicly available survey microdata source like the Current Population Survey (CPS) and adjust its attributes such that it becomes statistical representative of tax data.[^1] We feel that, at this point in time, direct use of the PUF best allows us to accurately model the broadest array of policy reforms of interest to the Budget Lab.

The remainder of this section describes the steps we take to convert the raw PUF into a usable series of projected tax data files for use in our tax model.

## Historical Aging
It is 2024 at the time of this writing, but the most recently available PUF is from tax year 2015. Our projections require a more recent jump-off point. We overcome this problem by utilizing additional data sources which give us some hints about what the population of tax filers looked like in the years from 2015 through 2023. The first step, then, is *historical aging* – the process by which the PUF is updated (“aged”) to be statistically representative of a more recent tax year. Due to varying data quality at different intervals during this period 2015, there are three discrete steps within the historical aging process.

The first period is 2015-2017, years for which we have supplemental IRS statistics and consistent variable definitions throughout.[^2] To generate a historically aged PUF through 2017, we follow the method described in Section 2.2 of [Ricco (2020)](https://static1.squarespace.com/static/55693d60e4b06d83cf793431/t/5e2860d306f0a742d33c21ef/1579704531589/DataProcessingForPWBMTaxModule.pdf), which itself adapts an approach described [O’Hare (2009)](https://github.com/PSLmodels/taxdata/blob/1f5f317e37b41a233efd75fb94f436f923b3e2d1/doc/Stage1_Stage2_Methodology.pdf). The idea is that record weights are adjusted until the resulting data matches some specified “target” statistical characteristics, which allows us to extrapolate cross-sectional data in year t to some future year t+n without modeling the underlying longitudinal dynamics. In this case, the IRS provides [summary tabulations](https://www.irs.gov/statistics/soi-tax-stats-individual-income-tax-returns-complete-report-publication-1304) of income and deduction categories (both returns counts and dollar values) broken out by AGI group, and the joint distribution of filing status, age range, and AGI; we choose key record count statistics from these tabulations to as our reweighting targets.[^3] Then, adjustments for each record weight are determined as the result of a linear programming optimization problem, a full mathematical description of which can be found in Ricco (2022). This step updates the data to account for *extensive margin* changes in variables over the period (for example, the share of records between \$40,000 and \$50,000 in AGI with nonzero wage income). Finally, we rescale dollar-amount variable values to close any remaining gap – the intensive margin component of change over the period. The result is a historically aged 2017 PUF.  

The second discrete phase of historical aging is 2018-2019, years for which we have supplemental IRS tabulations but the introduction of a major tax reform creates inconsistencies in variable definitions.[^4] Among other changes, the Tax Cuts and Jobs Act (TCJA) increased the standard deduction and limited certain itemized deductions, which led tens of millions of filers to stop itemizing deductions. This change created a truncation problem wherein certain deductible expenses, like charitable deductions, are observable only if the filer has a sufficiently large amount of itemized deductions.[^5] Thus, for some key variables, the IRS tabulations after 2017 are measuring a different universe of filers and are not usable as a direct target. For these years, we take a different approach. First, we update record weights to reflect the composition of growth in the number of tax returns filed by marital status and age. The weights are scaled such that the growth rate of a tax unit reflects the underlying growth composition of the ages of its members. Next, after mapping all dollar-amount variables to one of ten income categories unaffected by TCJA changes, we scale variables by their respective category’s per-filer income growth.

The final phase of historical aging is 2020-2023.[^6] The first two years of this period are difficult to model because of the unique recession as well as policy changes which temporarily expanded the universe of filing tax units; for 2022 and 2023, detailed IRS tabulations do not yet exist. For this period, we rely on a combination of historical data sources to age the data. Record weights are first scaled by age- and marital status-specific population growth, as measured by the Social Security Administration (SSA). For income and deduction variables, we again assign each variable to one of 12 categories and scale by per-filer growth.[^7] For income variables, the data source is CBO’s supplemental revenue projections file, which provides actual and projected values for 1040 aggregates; for mortgage interest, we use historical mortgage interest paid as measured by the National Income and Product Accounts; for charitable contributions, we use [Giving USA](https://givingusa.org/?utm_source=Google&utm_medium=D%2BC%20Ads&utm_campaign=PaidSearch&gad_source=1&gclid=Cj0KCQjw8J6wBhDXARIsAPo7QA_r_X5FUzOPj40hr1ppaqg4cmxMjlGnobxnGmRm4SIUleuoqLeUlLsaAjW_EALw_wcB)’s estimate of total charitable contributions by household.

## Imputation: Non-filing Population
Some Americans are not required to file a tax return, usually because their income is too low. The PUF only contains records for those who file a tax return, but we are often interested in modeling the impact of reforms which would affect current-law non-filers (for example, a fully refundable CTC design). Therefore, we need to simulate the attributes of the non-filing population and add the resulting synthetic records to our dataset. Among existing tax microsimulation models, a common approach is to build tax units in the CPS microdata, determine which simulated tax units do not file returns, then append these records to the PUF; see Ricco (2020), [Perese (2017)](https://www.cbo.gov/system/files/115th-congress-2017-2018/presentation/52914-presentation.pdf),  Rohaly et al. (2005) for descriptions of this general approach. We rely on the work of [Piketty et al. (2018)](https://gabriel-zucman.eu/usdina/), who also use the CPS for this step in their construction of microdata underlying a system of distributional national accounts. We append imputed non-filers from their 2017 public-use microdata file.[^8]

## Imputation: Other Variables
Some variables required to accurately calculate taxes under current law or counterfactual policy reform scenarios are incomplete or missing entirely from the PUF. It also lacks key demographic information useful for projecting the composition of taxpayers into the future. We add several additional variables via statistical imputation.[^9] Major variables include:
- **Age.** Taxpayer age is critical for both accurate tax calculation (some tax provision explicitly condition on age) and population projections (expected shifts in the age distribution will affect total revenues over time). The demographic supplement to the PUF file provides age ranges for primary filers for about two thirds of records; no information is available for the remaining records, nor is any information available on the age of secondary filers in the case of joint returns. To impute age, we begin by comparing the observed number of filers in a given age range/filing status group to that of administrative totals from IRS tabulations. The residual amount is the target for the imputation; we randomly assign age ranges until those are totals are met.[^10] Next, we impute age actual ages conditional on range. For each range, we estimate the distribution of age ranges using CPS data and draw from these distributions. Finally, we impute ages for secondary filers by estimating the distribution of age gaps in marriages and drawing from this distribution for joint returns.

 - **Dependent ages.** We follow a similar process for imputing dependent ages, ranges for which are available only for a subset of records and sometimes available only for a subset of dependents on a given return. We begin by imputing age ranges for each dependent who does not have an associated range. Probability distributions are broken out by type of dependent (child at home, child away from home, parent, and other) and are estimated on returns with one dependent only, which allows us to precisely map dependent type to age range.[^11] Then, we estimate probability distributions for within-range ages on CPS data and draw from those distributions to impute specific dependent ages.

 - **Gender.** As with age ranges, we observe gender only for a subset of tax returns. Gender is an important mediator of labor market outcomes and as such is a critical input when modeling behavioral responses involving labor supply and earnings. We impute gender by estimating the target male share of adults by filing status, presence of dependents, and presence of wage income on the microdata files underlying Piketty et al. (2018), then randomly drawing from these distributions for records without gender information.

 - **Earnings split.** Payroll taxes are applied at the individual level, but our unit of analysis in the PUF is the tax return. For joint returns in the PUF, individual characteristics like wages and business income are aggregated to the tax return level, though we do have some information on earnings split through the demographic file. To impute earnings split for the remaining filers, we draw from implied distributions from tabulations of the wage and self-employment earnings split for join returns by earnings percentile from [Saez (2016)](https://www.irs.gov/pub/irs-soi/16rpsaeztabulations.pdf).

 - **Pass-through characteristics.** The value of the Qualified Business Income (QBI) deduction depends on a business’s industry characteristics and its wage and capital structure. Because the most recent PUF tax year is 2015 but this provision was introduced in 2018, we have none of this information at the micro level and must impute it. First, we assume that 20 percent of pass-through business owners derive their income from a Specified Service Trade or Business (SSTB), a designation that makes the taxpayer ineligible for the QBI deduction if their taxable income is sufficiently high. Next, we impute employer status for each pass-through owner: did your business pay wages to an employee? Probability estimates for this step are taken from [Prisinzano et al. (2016)](https://home.treasury.gov/system/files/131/TP4-Update.pdf). Then, we collect IRS data on aggregate wages paid by legal pass-through entity type (sole proprietorship, partnership, S corporation). We allocate these wages to wage-paying business owners, with 50 percent being allocated equally and the rest being allocated in proportion to positive net income. The final step is to calibrate our imputations such that we broadly match the observed QBI deduction values for 2018 using employer probability as a free parameter. While our estimates match historical aggregates and CBO projections, this closeness is largely by construction. Our methods may not be robust to reforms which dramatically alter the nature of the QBI deduction.

## Future Aging
To project the tax data beyond the most recent year of historical data (2023 at the time of this writing), we generally rely on CBO’s projections.[^12] Our method is identical to that of historical aging during the period 2020-2023 as described above, only we use projected values rather than historical data. For demographics, we rely on CBO’s projections of SSA-concept population subgroups. For income and deduction variables, we begin with CBO’s projections of 1040 variables in the Budget Outlook’s supplemental revenue projections. For years beyond the budget window, we rely on CBO’s Long-Term Budget Outlook, again mapping PUF variables to broad economic aggregates.

Note that we are not bound to CBO’s economic projections. If, for example, we wish to understand the revenue impacts of population aging over the coming decade , we can supply an alternative projection of demographic trends and run the tax model on the resulting microdata. In that sense, economic projections are a parameterizable feature of the model.


### Footnotes
[^1]: See [PolicyEngine](https://blog.policyengine.org/enhancing-the-current-population-survey-for-policy-analysis-9a7d8e405daa) for an example of this kind of approach.

[^2]: Corresponding code is found in [`process_targets.R`](https://github.com/Budget-Lab-Yale/Tax-Data/blob/main/src/process_targets.R), [`reweight.R`](https://github.com/Budget-Lab-Yale/Tax-Data/blob/main/src/reweight.R), and [`create_2017_puf.R`](https://github.com/Budget-Lab-Yale/Tax-Data/blob/main/src/create_2017_puf.R).

[^3]: A full list of our baseline targets can be found [here](https://github.com/Budget-Lab-Yale/Tax-Data/blob/main/config/target_info/baseline.csv).

[^4]: Code for aging these years can be found in [`project_puf.R`](https://github.com/Budget-Lab-Yale/Tax-Data/blob/main/src/project_puf.R).

[^5]: Of course, this truncation problem existed prior to TCJA as well, albeit to a much smaller degree. It’s only a problem for our purposes if we wish to score proposals which expand the universe of itemizers. Because TCJA is temporary and the pre-TCJA itemizing rules are current law starting in 2026, we need to project the pre-TCJA-concept for each itemized deduction variable.

[^6]: Code for aging these years can be found in [`project_puf.R`](https://github.com/Budget-Lab-Yale/Tax-Data/blob/main/src/project_puf.R).

[^7]: Specific variable mappings can be found [here]().

[^8]: See [`imput_nonfilers.R`](https://github.com/Budget-Lab-Yale/Tax-Data/blob/main/src/impute_nonfilers.R) for corresponding model code.

[^9]: The code for these imputations can be found [here](https://github.com/Budget-Lab-Yale/Tax-Data/blob/main/src/process_puf.R).

[^10]: The code for this portion of the imputation process can be found [here](https://github.com/Budget-Lab-Yale/Tax-Data/blob/main/src/process_puf.R).

[^11]: See [this script](https://github.com/Budget-Lab-Yale/Tax-Data/blob/main/src/process_puf.R) for model code.

[^12]: Code for aging these years can be found in [`project_puf.R`](https://github.com/Budget-Lab-Yale/Tax-Data/blob/main/src/project_puf.R).
