---
title: "Tax Calculator"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The result of the previous section is a time series of simulated tax microdata for future years. This data is the input to the tax calculator – the model component which calculates policy-dependent tax variables for all records. Code for the functions described in this section can be found [here](https://github.com/Budget-Lab-Yale/Tax-Simulator/tree/main/src/calc).

The tax calculator is not unlike tax preparation software: given some information about a household’s characteristics (such as wages, mortgage interest, and marital status), the tax calculator returns tax liability. Crucially, the tax calculator is parameterized. Every major tax parameter is exposed to the user as an input variable. For example, rather than hard-code the CTC value as $2,000, the tax calculator includes a parameter called “ctc_value”, which can take on any value.) This way, users can define a policy scenario by supplying the calculator with the full set of parameters needed to characterize tax law. Current law, the notion of baseline used in scorekeeping convention, is just one instance of a policy scenario configuration. Users can also write new code to characterize policy reforms for which no current-law parameter exists, such as a progressive surcharge on AGI or a charitable credit.

In addition to a payroll tax module, we incorporate all major elements of individual income taxes. Calculator functions are split into one of four categories:

1. Income determination: taxable capital gains, taxable Social Security benefits, AGI, taxable income

2. Deductions: standard deduction, itemized deductions, QBI deduction, personal exemptions

3. Tax liability: ordinary rates, preferred rates, Alternative Minimum Tax (AMT), Net Investment Income Tax (NIIT)

4. Credits against tax: Saver's Credit, Child and Dependent Care Credit (CDCTC), education credits, Child Tax Credit (CTC), Earned Income Tax Credit (EITC), rebate/UBI/stimulus check

These functions rely on two types of input information. The first is the input attributes of a tax unit(s); for example, in the case of the CTC calculator function, this would be number of dependents, earnings, AGI, and more. The second kind of required information is tax law parameters; in the CTC example, this information would include the maximum credit value per child, the phase-in rate, the maximum age, and more. Again, tax law information is supplied as arguments to the function (rather than be hard-coded into the function) so that we can flexibly supply different tax law scenarios to the code to examine the impact of policy changes. In the model, tax law information is conveyed via a structured set of configuration files. More information on how these files are structured can be found in the Technical Implementation section below.

The tax calculator also contains functionality to estimate different kinds of tax rates. The effective marginal tax rate (EMTR) is defined as the additional amount of tax paid on the next dollar of some type of income. For example, if earning one more dollar of wages increases tax liability by 25 cents, the EMTR is 25 percent. EMTRs often depart from statutory marginal tax rates due to phase-in and phase-out structures within the tax code. The tax calculator measures EMTRs by adding one dollar to a given income (or expense) variable for all records then recalculating taxes; the change in taxes is the EMTR. We can also measure other types of tax rates, for example first-dollar EMTRs (by calculating the difference between taxes when some variable is set to \$0 and \$1) and average effective tax rates (by setting some income variable of initial value \$Y to \$0, recalculating taxes, then dividing the change in taxes by -$Y).