---
indexation_defaults:
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year:
    '2014': 1987
    '2018': 2017
  i_direction: -1
  i_increment: 50

# Base value for single filers
value_single:
  value:
    '2014': 3000
    '2018': 12000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
# Base value for HOH filers
value_head:
  value:
    '2014': 4400
    '2018': 18000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# Additional other bonus
bonus_other:
  value:
    '2014': 0
    '2025': 1000
    '2029': 0

# Elderly temporary bonus
bonus_elderly_temp_value:
  value: 
    '2024': 0
    '2025': 4000
    '2029': 0
