---

# Deduction rate
rate:
  value: 
    '2014': 0.0
    '2018': 0.2
    '2026': 0.23

# Phaseout type: 0 = TCJA design, 1 = May 2025 House-passed OBBB design
po_type:
  value: 
    '2014': 0
    '2026': 1

# Share of ordinary taxable income limit
txbl_inc_limit:
  value: 
    '2014': 0.2
    '2026': 0.23
    