---

# AGI limit for cash contributions, itemized deduction
item_cash_limit_agi:
  value:
    '2014': 0.5
    '2018': 0.6
    '2020': 1
    '2022': 0.6

# Maximum deductible above-the-line charitable contributions -- set to 0 for repeal
above_limit_single:
  value:
    '2014': 0
    '2020': 300
    '2022': 0
    '2025': 150
    '2029': 0
