---

filing_status_mapper:
  po_thresh:
    '1': po_thresh_single
    '2': po_thresh_married
    '3': po_thresh_married / 2
    '4': po_thresh_head
  po_range:
    '1': po_range_married / 2
    '2': po_range_married
    '3': po_range_married / 2
    '4': po_range_married / 2
  po_range_other:
    '1': po_range_other_married / 2
    '2': po_range_other_married
    '3': po_range_other_married / 2
    '4': po_range_other_married / 2
  baby_bonus_po_thresh:
    '1': baby_bonus_po_thresh_married / 2
    '2': baby_bonus_po_thresh_married
    '3': baby_bonus_po_thresh_married / 2
    '4': baby_bonus_po_thresh_married / 2
  value_old:
    '1': value_old_else
    '2': value_old_else
    '3': value_old_mfs
    '4': value_old_else 
  value_young:
    '1': value_young_else
    '2': value_young_else
    '3': value_young_mfs
    '4': value_young_else 

# Whether SSN is required to qualify for CTC
need_ssn:
  value:
    '2014': 0
    '2018': 1
    '2021': 0
    '2022': 1

# Maximum credit value per "young" child, non-MFS returns
value_young_else:
  value: 
    '2014': [1000, 0]
    '2018': [2000, 0]
    '2021': [2000, 1600]
    '2022': [2000, 0]
    '2025': [2500, 0]
    '2029': [2000, 0]
  i_measure: 
    '1987': cpi
    '2017': chained_cpi
  i_base_year:
    '2013': [NA, NA]
    '2029': [2024, 2024]
  i_direction: [-1, -1]
  i_increment: [100, 100]

# Maximum credit value per "old" child, non-MFS returns
value_old_else:
  value:
    '2014': [1000, 0]
    '2018': [2000, 0]
    '2021': [2000, 1000]
    '2022': [2000, 0] 
    '2025': [2500, 0] 
    '2029': [2000, 0]
  i_measure: 
    '1987': cpi
    '2017': chained_cpi
  i_base_year:
    '2013': [NA, NA]
    '2029': [2024, 2024]
  i_direction: [-1, -1]
  i_increment: [100, 100]
  
# Maximum credit value per "young" child, MFS returns
value_young_mfs:
  value: 
    '2014': [1000, 0]
    '2018': [2000, 0]
    '2021': [2000, 1600]
    '2022': [2000, 0]
    '2025': [0, 0]

# Maximum credit value per "old" child, MFS returns
value_old_mfs:
  value:
    '2014': [1000, 0]
    '2018': [2000, 0]
    '2021': [2000, 1000]
    '2022': [2000, 0] 
    '2025': [0, 0]

# AGI threshold above which credit value phases out, single filers
po_thresh_single:
  value:
    '2014': [75000, Inf]
    '2018': [200000, Inf]
    '2021': [200000, 75000]
    '2022': [200000, Inf]
    
# AGI threshold above which credit value phases out, joint filers
po_thresh_married:
  value:
    '2014': [110000, Inf] 
    '2018': [400000, Inf]
    '2021': [400000, 150000]
    '2022': [400000, Inf]
    
# AGI threshold above which credit value phases out, HoH filers
po_thresh_head:
  value:
    '2014': [75000, Inf]
    '2018': [200000, Inf]
    '2021': [200000, 112500]
    '2022': [200000, Inf]
    
# Maximum credit value per nonqualifying dependent (assumed to phaseout per po_thresh1)
value_other:
  value:
    '2014': 0
    '2018': 500

# Minimum refundable CTC per qualifying young child (i.e. y-intercept in trapezoid)
min_refund_young:
  value: 
    '2014': 0
    '2021': 3600
    '2022': 0
  
# Minimum refundable CTC per qualifying old child (i.e. y-intercept in trapezoid)
min_refund_old:
  value: 
    '2014': 0
    '2021': 3000
    '2022': 0

# Maximum refundable CTC per young qualifying child (inf implies maximum refund 
# is equal to the credit value)
max_refund_young:
  value:
    '2014': Inf
    '2018': 1400
    '2021': Inf
    '2022': 1400
  i_measure: 
    '1987': cpi
    '2017': chained_cpi
  i_base_year: 2017
  i_direction: -1
  i_increment: 100
  
# Maximum refundable CTC per old qualifying child (inf implies maximum refund 
# is equal to the credit value)
max_refund_old:
  value:
    '2014': Inf
    '2018': 1400
    '2021': Inf
    '2022': 1400
  i_measure: 
    '1987': cpi
    '2017': chained_cpi
  i_base_year: 2017
  i_direction: -1
  i_increment: 100

# Earned income threshold above which CTC phases in
pi_thresh:
  value:
    '2014': 3000
    '2018': 2500
