---
# Must include full filing_status_mapper since we're adding value_married
filing_status_mapper:
  value:
    '1': value_single
    '2': value_married
    '3': value_single
    '4': value_head
  bonus:
    '1': bonus_single
    '2': bonus_married
    '3': bonus_single
    '4': bonus_single
  bonus_other:
    '1': bonus_other
    '2': bonus_other * 2
    '3': bonus_other
    '4': bonus_other * 1.5

# Married standard deduction: $40k in 2026, reverting to 2x single in 2031
value_married:
  value:
    '2014': 6000
    '2018': 24000
    '2026': 40000
    '2031': 31500
  i_measure: default
  i_base_year:
    '2014': 1987
    '2018': 2017
    '2026': 2025
    '2031': 2024
  i_direction: default
  i_increment: 100
