---
filing_status_mapper:
  brackets:
    '1': brackets_single
    '2': brackets_married
    '3': brackets_married / 2
    '4': brackets_single

# Whether whether active earnings of pass-through businesses are subject to the NIIT
include_active:
  value: 0

# Rate schedule
rates:
  value:
    '2014': [0.0, 0.038]

# Brackets, single filers
brackets_single:
  value:
    '2014': [0, 200000]

# Brackets, joint filers
brackets_married:
  value:
    '2014': [0, 250000]
