---
indexation_defaults:
  i_measure:
    '1986': cpi
    '2017': chained_cpi
  i_base_year: 2023
  i_direction: -1
  i_increment: 100

# Phase-in rate
pi_rate: 
  value: 
    '2014': 0
    '2024': 0.2

# Earnings amount at which phase-in ends
pi_end: 
  value: 10000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
 
# Phase out rate 
po_rate:
  value: 0.2    
  
# Earnings amount at which credit begins to phase out
po_thresh:
  value: 15000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
