---

# Whether basis on appreciated property is carried over to decedent 
# (as opposed to stepped up to market value as per current law)
carryover_basis:
  value: 
    '2014': 0
    '2025': 1

# Preferred tax rate schedule 
rates:
  value: 
    '2014': [0.0, 0.15, 0.20]
    '2025': [0.05, 0.2, 0.25]
    