value_old:
  value:
    '2014':
    - 1000
    - 0
    '2018':
    - 2000
    - 0
    '2021':
    - 2000
    - 1000
    '2022':
    - 2000
    - 0
    '2026':
    - 3000
    - 0
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
value_young:
  value:
    '2014':
    - 1000
    - 0
    '2018':
    - 2000
    - 0
    '2021':
    - 2000
    - 1000
    '2022':
    - 2000
    - 0
    '2026':
    - 3000
    - 0
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
young_level:
  value:
    '2014': 1
    '2026': 0
bonus_young:
  value:
    '2014':
    - 0
    - 0
    '2026':
    - 1200
    - 0
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
min_refund_level:
  value:
    '2014': 1
    '2026': 0
min_refund_share:
  value: 1
pi_type:
  value:
    '2014': 1
    '2026': 0
pi_range:
  value: 10000
pi_thresh:
  value:
    '2014': 3000
    '2018': 2500
    '2026': 0
po_thresh_single:
  value:
    '2014':
    - 75000
    - Inf
    '2018':
    - 200000
    - Inf
    '2021':
    - 200000
    - 75000
    '2022':
    - 200000
    - Inf
    '2026':
    - Inf
    - Inf
po_thresh_married:
  value:
    '2014':
    - 110000
    - Inf
    '2018':
    - 400000
    - Inf
    '2021':
    - 400000
    - 150000
    '2022':
    - 400000
    - Inf
    '2026':
    - Inf
    - Inf
po_thresh_head:
  value:
    '2014':
    - 75000
    - Inf
    '2018':
    - 200000
    - Inf
    '2021':
    - 200000
    - 112500
    '2022':
    - 200000
    - Inf
    '2026':
    - Inf
    - Inf
value_other:
  value:
    '2014': 0
    '2018': 500
indexation_defaults:
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year:
    '2014': NA
    '2026':
    - 2025
    - 2025
  i_direction:
    '2014': NA
    '2026':
    - -1
    - -1
  i_increment:
    '2014': NA
    '2026':
    - 100
    - 100
