---
indexation_defaults:
  i_measure:
    '1986': cpi
    '2017': chained_cpi
  i_base_year:
    '2014': 2011
    '2018': 2017
  i_direction: 0
  i_increment: 100

# AMT exemption, single filers
exempt_single:
  value:
    '2014': 50600
    '2018': 70300
  i_measure: default
  i_base_year: 
    '2014': 2011
    '2018': 2017
    '2026': 2025
  i_direction: default
  i_increment: default

# AMT exemption, joint filers
exempt_married:
  value:
    '2014': 78750
    '2018': 109400
  i_measure: default
  i_base_year: 
    '2014': 2011
    '2018': 2017
    '2026': 2025
  i_direction: default
  i_increment: default

# AMT taxable income threshold above which exemption phases out, single filers
exempt_po_thresh_single:
  value: 
    '2014': 112500
    '2018': 500000
  i_measure: default
  i_base_year: 
    '2014': 2011
    '2018': 2017
    '2026': 2025
  i_direction: default
  i_increment: default
  
# AMT taxable income threshold above which exemption phases out, married filers
exempt_po_thresh_married:
  value:
    '2014': 150000
    '2018': 1000000
  i_measure: default
  i_base_year: 
    '2014': 2011
    '2018': 2017
    '2026': 2025
  i_direction: default
  i_increment: default
  
# AMT taxable income threshold above which exemption phases out, married filing separately returns
exempt_po_thresh_mfs:
  value:
    '2014': 75000
    '2018': 500000
  i_measure: default
  i_base_year: 
    '2014': 2011
    '2018': 2017
    '2026': 2025
  i_direction: default
  i_increment: default
