#-------------------------------------------------------------------------------
# write_widowhood_shares.R
#
# Writes config/calibrations/estate/widowhood.yaml: the probability that an
# unmarried person is widowed rather than never married, separated or divorced,
# by age band and sex, from the raw SCF.
#
# The model uses this to decide whether a single filer facing the death-gain
# exclusion can claim the married amount through a survivor election. Widowhood
# is an upper bound on that eligibility: a real regime requires the election to
# have been made, and some widows' spouses left no unused exclusion.
#
# The universe is unmarried respondents, marital status (X8023) separated (3),
# divorced (4), widowed (5) or never married (6). Respondents living with a
# partner are coded married in the SCF and excluded with them. Sex and age come
# from the summary extract (HHSEX, AGE), weights from the raw file (X42001),
# pooled over all five implicates.
#
# The chosen inputs, the survey year and the age band lower bounds, are in
# config/calibrations/estate/settings.yaml. Re-run this script through sbatch
# when either changes, and commit the regenerated file.
#
# Usage: Rscript other/estate_tax/write_widowhood_shares.R
#-------------------------------------------------------------------------------

suppressPackageStartupMessages({
  library(haven)
  library(data.table)
  library(dplyr)
  library(yaml)
})

script_dir = dirname(sub('--file=', '', grep('--file=', commandArgs(), value = TRUE)))
repo_root  = normalizePath(file.path(script_dir, '..', '..'))
calib_dir  = file.path(repo_root, 'config', 'calibrations', 'estate')

settings  = read_yaml(file.path(calib_dir, 'settings.yaml'))
scf_year  = settings$widowhood_scf_year$value
band_lo   = as.integer(settings$widowhood_age_band_lower_bounds$value)
stopifnot(length(band_lo) >= 2, !is.unsorted(band_lo, strictly = TRUE))

scf_dir   = file.path('/nfs/roberts/project/pi_nrs36/shared/raw_data/SCF/v1',
                      scf_year, 'historical')
raw_path  = file.path(scf_dir, sprintf('p%si6.dta', substr(scf_year, 3, 4)))
scfp_path = file.path(scf_dir, sprintf('SCFP%s.csv', scf_year))

# Marital status and weight from the raw file, all five implicates
raw = haven::read_dta(raw_path)
names(raw) = toupper(names(raw))
raw = as.data.table(raw)[, .(Y1, X8023, X42001)]

# Sex and age from the summary extract, keyed on the implicate id
scfp = fread(scfp_path, select = c('Y1', 'HHSEX', 'AGE'))

d = merge(raw, scfp, by = 'Y1')
stopifnot(nrow(d) == nrow(raw))

# Weighted share widowed among the unmarried, by age band and sex
d = d[X8023 %in% 3:6]
d[, band := findInterval(AGE, band_lo)]
d[band < 1, band := 1]

shares = d[, .(p_widow = sum(X42001 * (X8023 == 5)) / sum(X42001),
               n       = .N),
           by = .(band, HHSEX)]

n_bands = length(band_lo)
grid = as.data.table(expand.grid(band = 1:n_bands, HHSEX = 1:2))
shares = merge(grid, shares, by = c('band', 'HHSEX'), all.x = TRUE)
if (anyNA(shares$p_widow)) {
  stop('write_widowhood_shares: an age band by sex cell is empty; ',
       'coarsen widowhood_age_band_lower_bounds in settings.yaml')
}
shares = shares[order(band, HHSEX)]

hi = c(band_lo[-1] - 1L, NA)   # NA writes as .na, read back as Inf

header = c(
  '# Widowhood shares among the unmarried, by age band and sex',
  '#',
  '# The probability that an unmarried person is widowed rather than never',
  '# married, separated or divorced. Read by the kg_dynamics death-gain',
  '# exclusion to decide whether a single filer can claim the married amount',
  '# through a survivor election; an upper bound on that eligibility. These',
  '# measure the data rather than stating tax law, and a reform must never',
  '# override them.',
  '#',
  '# Generated by other/estate_tax/write_widowhood_shares.R, not written by',
  sprintf('# hand, from the %s SCF (marital status X8023, weight X42001; sex and',
          scf_year),
  '# age from the summary extract). Chosen inputs are in',
  '# config/calibrations/estate/settings.yaml.',
  ''
)

body = list(
  survey_year = as.integer(scf_year),
  universe    = paste('unmarried respondents, X8023 in {3,4,5,6};',
                      'p_widow is the weighted share widowed (X8023 == 5)'),
  bands = list(
    lo             = band_lo,
    hi             = hi,
    p_widow_male   = round(shares[HHSEX == 1]$p_widow, 6),
    p_widow_female = round(shares[HHSEX == 2]$p_widow, 6),
    n_male         = shares[HHSEX == 1]$n,
    n_female       = shares[HHSEX == 2]$n
  )
)

out_path = file.path(calib_dir, 'widowhood.yaml')
writeLines(c(header, as.yaml(body, indent.mapping.sequence = TRUE)), out_path)
cat('Wrote', out_path, '\n')
print(as.data.frame(body$bands), row.names = FALSE)
