#-------------------------------------------------------------------------------
# write_frozen_params.R
#
# Generates the on-model frozen estate measurement resource
# (config/calibrations/estate/bridge.yaml) from:
#   - the calibrated valuation parameters in
#     other/estate_tax/estate_valuation_params.yaml (r, rho_pt, cluster cap)
#   - the SOI-estimated per-bin inputs at the forward-year convention: death
#     year 2022 (latest observed), $12.06M exemption — exactly the calibrator's
#     `soi_in_fwd` (calibrate_estate_v2.R line 136)
#
# gamma is written as a SINGLE SCALAR for all scenarios: the SOI selection
# contamination (taxable-because-of-gifts bins near the exemption) is a
# property of the historical data generated under 2022 law, NOT of a reform's
# exemption, so re-pooling per reform exemption would pool from polluted bins.
# Documented caveat: low-exemption reforms ($3.5M-class) understate
# gift-driven payers (known accepted residual, thoughts doc §10h).
#
# Re-run this script (via sbatch) whenever the calibration is re-estimated or
# the SOI table is extended; commit the regenerated yaml.
#
# Usage: Rscript other/estate_tax/write_frozen_params.R
#-------------------------------------------------------------------------------

script_dir = dirname(sub('--file=', '', grep('--file=', commandArgs(), value = TRUE)))
source(file.path(script_dir, 'estate_module.R'))
suppressPackageStartupMessages(library(yaml))

repo_root = normalizePath(file.path(script_dir, '..', '..'))

FWD_DEATH_YEAR = 2022      # latest observed SOI death year
FWD_EXEMPTION  = 12.06e6   # BEA for that death year (calibrate_estate_v2.R BEA_HIST)

# Calibrated valuation parameters (single source of truth = calibration output)
cal = read_yaml(file.path(script_dir, 'estate_valuation_params.yaml'))

# Per-bin assumed parameters + pooled gamma at the forward-year convention
soi = load_soi_estate_table(file.path(script_dir, 'estate_tax_filed_2016_2023.csv'))
soi_fwd = soi_inputs(soi, FWD_DEATH_YEAR, exemption = FWD_EXEMPTION,
                     gamma_pool_factor = cal$gamma_pool_factor)

bins = soi_fwd %>%
  transmute(size_bin, lo, hi,
            f_ded  = round(f_ded, 6),
            p_dsue = round(p_dsue, 6),
            f_dsue = round(f_dsue, 6))
gamma = round(soi_fwd$gamma[1], 6)

out_path = file.path(repo_root, 'config', 'calibrations', 'estate', 'bridge.yaml')
dir.create(dirname(out_path), recursive = TRUE, showWarnings = FALSE)

header = c(
  '# Frozen estate-tax MEASUREMENT parameters (NOT tax law)',
  '#',
  '# The bridge from Tax-Data economic wealth to reported gross estate, plus',
  '# the SOI-estimated per-bin assumed parameters, frozen at the latest',
  '# observed death year. Read by the on-model estate calculator',
  '# (src/calc/functions/tax/estate.R via src/sim/estate.R). Reforms must',
  '# never override these; estate tax LAW lives in',
  '# config/scenarios/tax_law/default/estate.yaml.',
  '#',
  '# GENERATED by other/estate_tax/write_frozen_params.R — do not hand-edit.',
  sprintf('# Sources: calibration %s (r/rho_pt, log estate_calib_17403421.out);',
          cal$calibration_date),
  sprintf('#          SOI death year %d at $%.2fM exemption (f_ded/DSUE/gamma).',
          FWD_DEATH_YEAR, FWD_EXEMPTION / 1e6),
  '# Status and residuals: other/estate_tax/new_estate_modeling_thoughts.md §10h.',
  ''
)

body = list(
  # reported_gross = economic_gross * r * [1 + (rho_pt - 1) * s_pt]
  r      = cal$r,
  rho_pt = cal$rho_pt,

  # Absolute cluster death-weight cap (Tax-Data donor-clone guard, §10f):
  # exact-gross clusters (n >= 2, gross > $5M) capped at this many expected
  # deaths. Value re-derived per Tax-Data vintage.
  cluster_death_weight_cap = cal$cluster_death_weight_cap,

  # Lifetime-gift add-back: base = taxable_estate + gamma * reported_gross.
  # Single scalar for ALL scenarios (see header of generator script).
  gamma = gamma,

  # Per-size-bin assumed parameters (bin assigned on reported gross):
  #   f_ded  : non-debt deductions / gross (debts subtracted explicitly)
  #   p_dsue : probability a single decedent claims DSUE (portability)
  #   f_dsue : average DSUE as a fraction of gross
  bins = list(
    size_bin = bins$size_bin,
    lo       = bins$lo,
    hi       = bins$hi,
    f_ded    = bins$f_ded,
    p_dsue   = bins$p_dsue,
    f_dsue   = bins$f_dsue
  ),

  # Provenance / staleness guard: the sim warns when run against a different
  # Tax-Data vintage (valuation params and cluster cap are vintage-specific)
  tax_data_vintage   = cal$tax_data_vintage,
  calibration_date   = cal$calibration_date,
  soi_death_year     = FWD_DEATH_YEAR,
  soi_exemption      = FWD_EXEMPTION
)

writeLines(c(header, as.yaml(body, indent.mapping.sequence = TRUE)), out_path)
cat('Wrote', out_path, '\n')
cat('gamma =', gamma, '\n')
print(as.data.frame(bins), row.names = FALSE)
