#-------------------------------------------------------------------------------
# write_frozen_params.R
#
# Merges the estate measurement bridge the model reads,
# config/calibrations/estate/bridge.yaml, out of three inputs:
#   - the fitted valuation parameters r and rho_pt from
#     config/calibrations/estate/valuation_fit.yaml, written by
#     calibrate_estate_v2.R
#   - the chosen inputs from config/calibrations/estate/settings.yaml: the cluster
#     cap, the gift-pooling guard, and which death year and exemption to freeze at
#   - the SOI per-bin inputs at that forward-year convention
#
# The gift add-back gamma is written as one scalar for every scenario. The SOI
# selection contamination, from bins near the exemption that are taxable because of
# gifts, is a property of the historical data generated under 2022 law rather than
# of a reform's exemption, so re-pooling per reform exemption would pool from
# contaminated bins. Reforms with an exemption near $3.5M therefore understate
# gift-driven payers, an accepted residual recorded in
# other/estate_tax/new_estate_modeling_thoughts.md section 10h.
#
# Re-run this script through sbatch whenever the calibration is re-estimated or the
# SOI table is extended, and commit the regenerated file.
#
# Usage: Rscript other/estate_tax/write_frozen_params.R
#-------------------------------------------------------------------------------

script_dir = dirname(sub('--file=', '', grep('--file=', commandArgs(), value = TRUE)))
source(file.path(script_dir, 'estate_module.R'))
suppressPackageStartupMessages(library(yaml))

repo_root = normalizePath(file.path(script_dir, '..', '..'))

calib_dir = file.path(repo_root, 'config', 'calibrations', 'estate')

# The two fitted parameters, straight from the file the calibrator writes.
fit      = read_yaml(file.path(calib_dir, 'valuation_fit.yaml'))
settings = read_yaml(file.path(calib_dir, 'settings.yaml'))

cal = list(
  r                        = fit$r$value,
  rho_pt                   = fit$rho_pt$value,
  cluster_death_weight_cap = settings$cluster_death_weight_cap$value,
  gamma_pool_factor        = settings$gamma_pool_factor$value,
  # The fit records the vintage it was made under; the bridge carries that
  # forward, which is what lets the model tell you it is looking at estate
  # parameters derived on different microdata than the run is using.
  tax_data_vintage         = fit$r$derived_under$tax_data,
  calibration_date         = fit$r$set
)

# Both entries of the fit must agree about the world they came from. They are
# fitted jointly, so a disagreement means one was written by a run the other did
# not take part in.
if (!identical(fit$r$derived_under, fit$rho_pt$derived_under) ||
    !identical(fit$r$set, fit$rho_pt$set)) {
  stop('valuation_fit.yaml: r and rho_pt disagree about their derivation (set ',
       'date or derived_under). They are fitted jointly by ',
       'calibrate_estate_v2.R, so one of them is left over from an earlier run. ',
       'Re-run the calibration rather than reconciling by hand.')
}

FWD_DEATH_YEAR = settings$soi_death_year$value   # latest observed SOI death year
FWD_EXEMPTION  = settings$soi_exemption$value    # exemption in force that year

# Per-bin assumed parameters + pooled gamma at the forward-year convention
soi = load_soi_estate_table(file.path(script_dir, 'estate_tax_filed_2016_2023.csv'))
soi_fwd = soi_inputs(soi, FWD_DEATH_YEAR, exemption = FWD_EXEMPTION,
                     gamma_pool_factor = cal$gamma_pool_factor)

bins = soi_fwd %>%
  transmute(size_bin, lo, hi,
            f_ded  = round(f_ded, 6),
            p_dsue = round(p_dsue, 6),
            f_dsue = round(f_dsue, 6))
gamma = round(soi_fwd$gamma[1], 6)

out_path = file.path(repo_root, 'config', 'calibrations', 'estate', 'bridge.yaml')
dir.create(dirname(out_path), recursive = TRUE, showWarnings = FALSE)

header = c(
  '# Frozen estate tax measurement parameters',
  '#',
  '# The bridge from Tax-Data economic wealth to reported gross estate, plus the',
  '# SOI per-bin parameters, frozen at the latest observed death year. Read by',
  '# the estate calculator in src/calc/functions/tax/estate.R. These measure the',
  '# data rather than stating tax law, and a reform must never override them.',
  '# Estate tax law is in config/scenarios/tax_law/default/estate.yaml.',
  '#',
  '# Generated by other/estate_tax/write_frozen_params.R, not written by hand.',
  '# Inputs: config/calibrations/estate/valuation_fit.yaml (fitted r/rho_pt,',
  '#         written by other/estate_tax/calibrate_estate_v2.R) and',
  '#         config/calibrations/estate/settings.yaml (the chosen inputs).',
  sprintf('# Sources: calibration %s (r/rho_pt);', cal$calibration_date),
  sprintf('#          SOI death year %d at $%.2fM exemption (f_ded/DSUE/gamma).',
          FWD_DEATH_YEAR, FWD_EXEMPTION / 1e6),
  '# Status and residuals: other/estate_tax/new_estate_modeling_thoughts.md section 10h.',
  ''
)

body = list(
  # reported_gross = economic_gross * r * [1 + (rho_pt - 1) * s_pt]
  r      = cal$r,
  rho_pt = cal$rho_pt,

  # Absolute cluster death-weight cap (Tax-Data donor-clone guard, §10f):
  # exact-gross clusters (n >= 2, gross > $5M) capped at this many expected
  # deaths. Value re-derived per Tax-Data vintage.
  cluster_death_weight_cap = cal$cluster_death_weight_cap,

  # Lifetime-gift add-back: base = taxable_estate + gamma * reported_gross.
  # Single scalar for ALL scenarios (see header of generator script).
  gamma = gamma,

  # Per-size-bin assumed parameters (bin assigned on reported gross):
  #   f_ded  : non-debt deductions / gross (debts subtracted explicitly)
  #   p_dsue : probability a single decedent claims DSUE (portability)
  #   f_dsue : average DSUE as a fraction of gross
  bins = list(
    size_bin = bins$size_bin,
    lo       = bins$lo,
    hi       = bins$hi,
    f_ded    = bins$f_ded,
    p_dsue   = bins$p_dsue,
    f_dsue   = bins$f_dsue
  ),

  # Provenance / staleness guard: the sim warns when run against a different
  # Tax-Data vintage (valuation params and cluster cap are vintage-specific)
  tax_data_vintage   = cal$tax_data_vintage,
  calibration_date   = cal$calibration_date,
  soi_death_year     = FWD_DEATH_YEAR,
  soi_exemption      = FWD_EXEMPTION
)

writeLines(c(header, as.yaml(body, indent.mapping.sequence = TRUE)), out_path)
cat('Wrote', out_path, '\n')
cat('gamma =', gamma, '\n')
print(as.data.frame(bins), row.names = FALSE)
