---
indexation_defaults:
  i_measure: 
    '1986': cpi
  i_base_year: 2012
  i_direction: -1
  i_increment: 50

filing_status_mapper:
  pease_thresh:
    '1': pease_thresh_single
    '2': pease_thresh_married
    '3': pease_thresh_married / 2
    '4': pease_thresh_head
  salt_limit:
    '1': salt_limit_married
    '2': salt_limit_married
    '3': salt_limit_married / 2
    '4': salt_limit_married
  mort_bal_limit:
    '1': mort_bal_limit_single
    '2': mort_bal_limit_married
    '3': mort_bal_limit_mfs
    '4': mort_bal_limit_single
  
# AGI floor above which medical expenses are deductible
med_floor_agi:
  value: 0.075

# Maximum medical expense deduction 
med_limit:
  value: Inf

# Maximum deductible state and local taxes, joint returns
salt_limit_married:
  value: Inf

# Years after which mortgage interest deduction is limited based on mortgage balance. Maps to mort_bal_limit 
mort_bal_limit_years:
  value: [1987, Inf]

# Limitations on deductible mortgage interest based on mortgage balance, single filers
mort_bal_limit_single:
  value: [Inf, 1000000]

# Limitations on deductible mortgage interest based on mortgage balance, joint filers
mort_bal_limit_married:
  value: [Inf, 1000000]

# Limitations on deductible mortgage interest based on mortgage balance, married filing separately filers
mort_bal_limit_mfs:
  value: [Inf, 500000]

# Maximum deductible mortgage interest
mort_int_limit:
  value: Inf

# Maximum deductible casualty and loss expenses
casualty_limit:
  value: Inf

# AGI floor for "miscellaneous" itemized deductions
misc_floor_agi:
  value: 0.02
  
# Maximum deductible "miscellanous" itemized deductions
misc_limit:
  value: Inf

# AGI threshold above which itemized deductions are limited under Pease, single filers
pease_thresh_single:
  value: 250000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# AGI threshold above which itemized deductions are limited under Pease, joint filers  
pease_thresh_married:
  value: 300000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default  
 
# AGI threshold above which itemized deductions are limited under Pease, head-of-household filers
pease_thresh_head:
  value: 275000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
# Pease limitation phaseout rate with respect to AGI
pease_rate:
  value: 0.03

# Maximum Pease phaseout, expressed as percent of tentative total deductions
pease_max_share:
  value: 0.8
  
# Maximum value of itemized deductions
limit:
  value: Inf
