---
indexation_defaults:
  i_measure: 
    '1986': cpi
  i_base_year: [1992, 2002, 1992, 1992, 1993, 1993, 2012]
  i_direction: [-1, -1, -1, -1, -1, -1, -1]
  i_increment: [50, 50, 50, 50, 50, 50, 50]

filing_status_mapper:
  brackets:
    '1': brackets_single
    '2': brackets_married
    '3': brackets_married / 2
    '4': brackets_head

# Ordinary tax rate schedule
rates:
  value: [0.1, 0.15, 0.25, 0.28, 0.33, 0.35, 0.396]

# Brackets for ordinary-rate income, single filers
brackets_single:
  value: [0, 7000, 22100, 53500, 115000, 250000, 400000]
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: [25, 25, 25, 25, 25, 25, 25]

# Brackets for ordinary-rate income, joint filers
brackets_married:
  value: [0, 14000, 44200, 89150, 140000, 250000, 450000]
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
# Brackets for ordinary-rate income, head of household filers
brackets_head:
  value: [0, 10000, 29600, 76400, 127500, 250000, 425000]
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
