---
filing_status_mapper:
  brackets:
    '1': brackets_single
    '2': brackets_married
    '3': brackets_single
    '4': brackets_single

# Rate at which benefits are added to modified AGI
magi_ss_rate:
  value: 0.5
  
# Benefit inclusion rates 
rates:
  value: [0.0, 0.5, 0.85]
  
# Benefit inclusion rate brackets for unmarried tax units 
brackets_single:
  value: [0, 25000, 34000]
  
# Benefit inclusion rate brackets for unmarried tax units 
brackets_married:
  value: [0, 32000, 44000]  
