---
indexation_defaults:
  i_measure:
    '1986': cpi
    '2017': chained_cpi
  i_base_year: 
    '2014': [1992, 1992, 2012]
    '2025': [1992, 1992, 2012, 2024]
  i_direction: 
    '2014': [-1, -1, -1]
    '2025': [-1, -1, -1, -1]
  i_increment: 
    '2014': [50, 50, 50]
    '2025': [50, 50, 50, 50]

# Preferred tax rate schedule 
rates:
  value: 
    '2014': [0.0, 0.15, 0.20]
    '2025': [0.0, 0.15, 0.20, 0.396]

# Brackets for preferred-rate income, single filers
brackets_single:
  value: 
    '2014': [0, 22100, 400000]
    '2025': [0, 22100, 400000, 1000000]
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: 
    '2014': [25, 25, 25] 
    '2025': [25, 25, 25, 50]

# Brackets for preferred-rate income, joint filers
brackets_married:
  value: 
    '2014': [0, 44200, 450000]
    '2025': [0, 44200, 450000, 1000000]
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
# Brackets for preferred-rate income, head of household filers
brackets_head:
  value: 
    '2014': [0, 29600, 425000]
    '2025': [0, 29600, 425000, 1000000]
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default


