---


filing_status_mapper:
  pease_thresh:
    '1': pease_thresh_single
    '2': pease_thresh_married
    '3': pease_thresh_married / 2
    '4': pease_thresh_head
  salt_limit:
    '1': salt_limit_married
    '2': salt_limit_married
    '3': salt_limit_married / 2
    '4': salt_limit_married
  salt_floor:
    '1': salt_floor
    '2': salt_floor
    '3': salt_floor / 2
    '4': salt_floor
  salt_floor_thresh:
    '1': salt_floor_thresh
    '2': salt_floor_thresh
    '3': salt_floor_thresh / 2
    '4': salt_floor_thresh
  mort_bal_limit:
    '1': mort_bal_limit_single
    '2': mort_bal_limit_married
    '3': mort_bal_limit_mfs
    '4': mort_bal_limit_single
  limit_tax_value_thresh:
    '1': limit_tax_value_thresh_single
    '2': limit_tax_value_thresh_married
    '3': limit_tax_value_thresh_single
    '4': limit_tax_value_thresh_single

# Maximum deductible state and local taxes, joint returns
salt_limit_married:
  value:
    '2014': Inf
    '2018': 10000
    '2025': 40000
    '2026': 40400
    '2027': 40804
    '2028': 41212
    '2029': 41624
    '2030': 42040
    '2031': 42461
    '2032': 42885
    '2033': 43314

# Minimum value of SALT deduction
salt_floor:
  value:
    '2014': 0
    '2025': 10000

# Income above which SALT deduction phases out towards the floor
salt_floor_thresh:
  value:
    '2014': Inf
    '2025': 500000
    '2026': 505000
    '2027': 510050
    '2028': 515151
    '2029': 520302
    '2030': 525505
    '2031': 530760
    '2032': 536068
    '2033': 541428

# Amount of SALT workaround that evades capture
salt_workaround_share:
  value:
    '2014': 1
    '2025': 0.2

# Years after which mortgage interest deduction is limited based on mortgage balance. Maps to mort_bal_limit 
mort_bal_limit_years:
  value: 
    '2014': [1987, Inf]
    '2018': [1987, 2017, Inf]

# Limitations on deductible mortgage interest based on mortgage balance, single filers
mort_bal_limit_single:
  value:
    '2014': [Inf, 1000000]
    '2018': [Inf, 1000000, 375000]

# Limitations on deductible mortgage interest based on mortgage balance, joint filers
mort_bal_limit_married:
  value:
    '2014': [Inf, 1000000]
    '2018': [Inf, 1000000, 750000]

# Limitations on deductible mortgage interest based on mortgage balance, married filing separately filers
mort_bal_limit_mfs:
  value:
    '2014': [Inf, 500000]
    '2018': [Inf, 500000, 375000]

# Whether deductions for non-primary residences are allowed
mort_int_non_prim:
  value: 
    '2014': 1
    '2025': 0

# Maximum deductible "miscellanous" itemized deductions
misc_limit:
  value:
    '2014': Inf
    '2018': 0

# Maximum deductible casualty and loss expenses
casualty_limit:
  value: 
    '2014': Inf
    '2018': 0
    
# AGI threshold above which itemized deductions are limited under Pease, single filers
pease_thresh_single:
  value:
    '2014': 250000
    '2018': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# AGI threshold above which itemized deductions are limited under Pease, joint filers  
pease_thresh_married:
  value:
    '2014': 300000
    '2018': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default  
 
# AGI threshold above which itemized deductions are limited under Pease, head-of-household filers
pease_thresh_head:
  value:
    '2014': 275000
    '2018': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
# Tax value limitation reduction threshold, nonjoint returns (i.e. next bracket where rate corresponding to maximum tax value ends)
limit_tax_value_thresh_single:
  value:
    '2014': Inf
    '2026': 500000
  i_base_year:
    '2014': NA
    '2026': 2017
  i_direction: -1
  i_increment: 25
    
# Tax value limitation reduction threshold, joint returns (i.e. next bracket where rate corresponding to maximum tax value ends)
limit_tax_value_thresh_married:
  value:
    '2014': Inf
    '2026': 600000
  i_base_year:
    '2014': NA
    '2026': 2017
  i_direction: -1
  i_increment: 50
  
# Tax value limitation reduction rate, SALT (i.e. percentage point diference between maximum statutory tax value and target value) 
salt_limit_tax_value_rate:
  value:
    '2014': 0
    '2026': 0.1351351

# Tax value limitation reduction rate, non-SALT (i.e. percentage point diference between maximum statutory tax value and target value) 
limit_tax_value_rate:
  value:
    '2014': 0
    '2026': 0.05405405
