---

# Maximum credit value per "young" child
value_young:
  value: 
    '2014': [1000, 0]
    '2018': [2000, 0]
    '2021': [2000, 1600]
    '2022': [2000, 0]
    '2024': [0, 0]

# Maximum credit value per "old" child
value_old:
  value:
    '2014': [1000, 0]
    '2018': [2000, 0]
    '2021': [2000, 1000]
    '2022': [2000, 0]
    '2024': [0, 0] 

# Maximum credit value per nonqualifying dependent (assumed to phaseout per po_thresh1)
value_other:
  value:
    '2014': 0
    '2018': 500
    '2024': 0
