---
indexation_defaults:
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year: 1995
  i_direction: 0
  i_increment: 10

filing_status_mapper:
  pi_end_0:
    '1': pi_end_0
    '2': pi_end_0 * pi_end_marriage_adj_0
    '3': pi_end_0
    '4': pi_end_0
  pi_end_1:
    '1': pi_end_1
    '2': pi_end_1 * pi_end_marriage_adj_1
    '3': pi_end_1
    '4': pi_end_1
  pi_end_2:
    '1': pi_end_2
    '2': pi_end_2 * pi_end_marriage_adj_1
    '3': pi_end_2
    '4': pi_end_2
  pi_end_3:
    '1': pi_end_3
    '2': pi_end_3 * pi_end_marriage_adj_1
    '3': pi_end_3
    '4': pi_end_3
  po_thresh_0:
    '1': po_thresh_0
    '2': po_thresh_0 + po_thresh_marriage_adj
    '3': po_thresh_0
    '4': po_thresh_0
  po_thresh_1:
    '1': po_thresh_1
    '2': po_thresh_1 + po_thresh_marriage_adj
    '3': po_thresh_1
    '4': po_thresh_1
  po_thresh_2:
    '1': po_thresh_2
    '2': po_thresh_2 + po_thresh_marriage_adj
    '3': po_thresh_2
    '4': po_thresh_2
  po_thresh_3:
    '1': po_thresh_3
    '2': po_thresh_3 + po_thresh_marriage_adj
    '3': po_thresh_3
    '4': po_thresh_3

# Credit phase-in rate for filers with no qualifying children 
pi_rate_0:
  value: 
    '2014': 0.0765
    '2021': 0.153
    '2022': 0.0765
    '2025': 0.125

# Credit phase-in rate for filers with 1 child  
pi_rate_1:
  value: 
    '2014': 0.34
    '2025': 0.1666667

# Credit phase-in rate for filers with 2 children
pi_rate_2:
  value: 
    '2014': 0.4
    '2025': 0.1666667

# Credit phase-in rate for filers with 3+ children  
pi_rate_3:
  value:
    '2014': 0.45
    '2025': 0.1666667

# Credit phase-out rate for filers with no children  
po_rate_0:
  value: 
    '2014': 0.0765
    '2025': 0.1429

# Credit phase-out rate for filers with 1 child  
po_rate_1:
  value: 
    '2014': 0.1598
    '2025': 0.1429
  
# Credit phase-out rate for filers with 2 children  
po_rate_2:
  value: 
    '2014': 0.2106
    '2025': 0.1429

# Credit phase-out rate for filers with 3+ children  
po_rate_3:
  value: 
    '2014': 0.2106
    '2025': 0.1429

# Earned income threshold at which credit is maximized for filers with no children 
pi_end_0:
  value:
    '2014': 4220
    '2021': 9820
    '2022': 4220
    '2025': 8000
  i_measure: default
  i_base_year:
    '2014': 1995
    '2021': 2020
    '2022': 1995
    '2025': 2024
  i_direction: default
  i_increment: default

# Earned income threshold at which credit is maximized for filers with 1 child 
pi_end_1:
  value: 
    '2014': 6330
    '2025': 12000
  i_measure: default
  i_base_year: 
    '2014': 1995
    '2025': 2024
  i_direction: default
  i_increment: default

# Earned income threshold at which credit is maximized for filers with 2 children 
pi_end_2:
  value: 
    '2014': 8890
    '2025': 12000
  i_measure: default
  i_base_year: 
    '2014': 1995
    '2025': 2024
  i_direction: default
  i_increment: default

# Earned income threshold at which credit is maximized for filers with 3+ children 
pi_end_3:
  value: 
    '2014': 8890
    '2025': 12000
  i_measure: default
  i_base_year: 
    '2014': 1995
    '2025': 2024
  i_direction: default
  i_increment: default

# Phase-in threshold multiplicative-factor for joint returns, filers with no children
# (Note that this param does not exist under the baseline! It is used only used in
# filing status mapper and not calculation code.) 
pi_end_marriage_adj_0:
  value: 
    '2014': 1
    '2025': 2

# Phase-in threshold multiplicative-factor for joint returns, filers with 1+ children
# (Note that this param does not exist under the baseline! It is used only used in
# filing status mapper and not calculation code.) 
pi_end_marriage_adj_1:
  value: 
    '2014': 1
    '2025': 1.5

# AGI threshold at which credit begins phasing out for filers with no children
po_thresh_0:
  value: 
    '2014': 5280
    '2021': 11610
    '2022': 5280
    '2025': 10000
  i_measure: 
  i_base_year:
    '2014': 1995
    '2021': 2020
    '2022': 1995
    '2025': 2024
  i_direction: default
  i_increment: default

# AGI threshold at which credit begins phasing out for filers with 1 child
po_thresh_1:
  value: 
    '2014': 11610
    '2025': 23000
  i_measure: default
  i_base_year: 
    '2014': 1995
    '2025': 2024
  i_direction: default
  i_increment: default

# AGI threshold at which credit begins phasing out for filers with 2 children
po_thresh_2:
  value: 
    '2014': 11610
    '2025': 23000
  i_measure: default
  i_base_year: 
    '2014': 1995
    '2025': 2024
  i_direction: default
  i_increment: default

# AGI threshold at which credit begins phasing out for filers with 3 children
po_thresh_3:
  value: 
    '2014': 11610
    '2025': 23000
  i_measure: default
  i_base_year: 
    '2014': 1995
    '2025': 2024
  i_direction: default
  i_increment: default

# Phaseout threshold add-factor for joint returns
po_thresh_marriage_adj:
  value: 
    '2014': 5000
    '2025': 10000
  i_measure: default
  i_base_year: 
    '2014': 2008
    '2025': 2024
  i_direction: default
  i_increment: default
