mort_bal_limit_years:
  value:
    '2014':
    - 1987
    - Inf
    '2018':
    - 1987
    - 2017
    - Inf
mort_bal_limit_single:
  value:
    '2014':
    - Inf
    - 1000000
    '2018':
    - Inf
    - 1000000
    - 375000
mort_bal_limit_married:
  value:
    '2014':
    - Inf
    - 1000000
    '2018':
    - Inf
    - 1000000
    - 750000
mort_bal_limit_mfs:
  value:
    '2014':
    - Inf
    - 500000
    '2018':
    - Inf
    - 500000
    - 375000
casualty_limit:
  value:
    '2014': Inf
    '2018': 0
misc_limit:
  value:
    '2014': Inf
    '2018': 0
pease_thresh_single:
  value:
    '2014': 250000
    '2018': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
pease_thresh_married:
  value:
    '2014': 300000
    '2018': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
pease_thresh_head:
  value:
    '2014': 275000
    '2018': Inf
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
