#!/bin/bash
#-----------------------------------------------------------------------
# launch_eta_dial_levels.sh  --  pin eta for the LEVELS (semi-elasticity) form.
#
# Runs the +5pp capital-gains shock (s_cg_r25, against its own baseline) at three
# trial eta values, so measure_efull_by_eta.R can measure E_full at each and
# invert for the eta that hits the target moment E_full = -0.6/0.238 = -2.52.
#
# WHY THIS SCRIPT IS NEW. The levels dial was run by hand in July 2026 -- the trial
# eta went in through the KG_ETA environment variable and the three vintages were
# launched one at a time from a shell. Nothing recorded which eta produced which
# vintage except the person doing it. The environment back doors are retired now, so
# a trial value is a FILE, bound by its own behavior alternative, named by its own
# runscript, all three generated by
#
#   python3 other/kg_model_tests/form_ab/write_eta_sweep.py levels
#
# which is also where the grid is declared. The tags match the vintages the
# 2026-07-12 re-pin wrote (eta_dial_e20_v2 / _c_v2 / _e30_v2) so a re-run is
# comparable against them point for point.
#
# THE ONE MANUAL STEP, and it is deliberate. `response_form` is a FIXED setting in
# config/calibrations/kg/settings.yaml -- one value for every scenario in a run --
# because each form has its own calibrated elasticity, and a run mixing them would
# pair one of them with the wrong number. The levels eta is DORMANT: the shipped
# setting is `logs`. So this sweep needs the setting flipped to `levels` first, and
# flipped back afterwards. This script refuses to launch until it is, because a
# levels sweep run under the logs form measures nothing.
#
# Full sample; delete_detail=1 keeps the conventional_no_wealth leg, which carries
# the E_full numerator. The measurement needs one vintage with FULL detail to supply
# the form-invariant base R and the shared-law dtau -- the central tag does that,
# which is why it is launched with delete_detail=0.
#
# After all three finish (Phase 3b), measure + invert + write the value:
#   sbatch other/top_tax/eta_dial/measure_efull_by_eta.sbatch
#
# SUBMIT THROUGH THE SBATCH WRAPPER, not from the login node -- slurm_run.sh's
# Phase 0 runs setup.R in process, which is real R work:
#
#   sbatch other/top_tax/eta_dial/launch_eta_dial_levels.sbatch [tag ...]
#
# Usage (from repo root):
#   bash other/top_tax/eta_dial/launch_eta_dial_levels.sh           # whole grid
#   bash other/top_tax/eta_dial/launch_eta_dial_levels.sh c         # one point
#   VINTAGE_SUFFIX=_spot bash .../launch_eta_dial_levels.sh c       # spot check
#
# VINTAGE_SUFFIX is not optional for a spot check. The vintage name derives from
# the tag, so re-running tag c with no suffix writes over the vintage the check is
# meant to compare against -- turning a verification into an overwrite.
#-----------------------------------------------------------------------
set -euo pipefail
cd /nfs/roberts/project/pi_nrs36/jar335/Repositories/Tax-Simulator

SETTINGS=config/calibrations/kg/settings.yaml

# The grid, straddling the shipped 2.4825. Tags match the sweep folders and the
# generated runscripts; all three have to agree with measure_efull_by_eta.R's
# `runs` table.
ALL_TAGS=(e20 c e30)

# The central tag keeps its detail: the measurement reads a full-detail baseline
# and conventional leg from exactly one vintage to get the form-invariant base R
# and the shared dtau.
CENTRAL_TAG=c

VINTAGE_SUFFIX="${VINTAGE_SUFFIX:-}"

# Refuse to run under the wrong form. Reading the setting rather than trusting the
# operator, because this is the failure that would produce a plausible-looking
# number measured under the other model.
form=$(grep -A1 '^response_form:' "$SETTINGS" | grep -oP '^\s+value:\s*\K\S+')
if [ "$form" != "levels" ]; then
  cat <<EOF
response_form is '$form' in $SETTINGS, and this sweep needs 'levels'.

The setting is fixed for the whole run on purpose: each response form has its own
calibrated elasticity, so a run cannot mix them. To sweep the levels eta:

  1. set  response_form: levels  in $SETTINGS
  2. re-run this script
  3. set it back to 'logs' when the measurement is done

Step 3 matters. Leaving it on 'levels' silently changes every capital-gains
scenario the model runs afterwards.
EOF
  exit 1
fi

if [ "$#" -gt 0 ]; then
  TAGS=("$@")
else
  TAGS=("${ALL_TAGS[@]}")
fi

for tag in "${TAGS[@]}"; do
  runscript="top_tax/eta_dial_levels_${tag}"
  vintage="eta_dial_levels_${tag}${VINTAGE_SUFFIX}"

  if [ ! -f "config/runscripts/${runscript}.csv" ]; then
    echo "No runscript at config/runscripts/${runscript}.csv."
    echo "Generate the grid first:"
    echo "  python3 other/kg_model_tests/form_ab/write_eta_sweep.py levels"
    exit 1
  fi

  if [ "$tag" = "$CENTRAL_TAG" ]; then delete_detail=0; else delete_detail=1; fi

  echo "launching levels eta-dial: tag ${tag} -> ${runscript}, vintage ${vintage} (delete_detail=${delete_detail})"
  bash slurm_run.sh "$runscript" NULL 1 "$vintage" 1 0 NULL "$delete_detail"
done

echo ""
echo "${#TAGS[@]} levels eta-dial vintage(s) launched. When all reach Phase 3b:"
echo "  KG_CALIB_OUTPUT_ROOT=... sbatch other/top_tax/eta_dial/measure_efull_by_eta.sbatch"
echo ""
echo "REMEMBER to set response_form back to 'logs' in $SETTINGS afterwards."
