---
indexation_defaults:
  i_measure:
    '1986': cpi
    '2017': chained_cpi
  i_base_year: 
    '2014': NA
    '2025': 2024
  i_direction:
    '2014': NA
    '2025': -1
  i_increment: 
    '2014': NA
    '2025': 100

# Maximum qualifying dependent age
dep_age_limit:
  value:
    '2014': 16
    '2021': Inf
    '2022': 16
    '2025': Inf

# Whether dependents are required to have an SSN to qualify
dep_ssn_req:
  value: 
    '2014': 1
    '2025': 0

# Credit value per adult
value:
  value: 
    '2014': 0
    '2020': 1800 
    '2021': 1400
    '2022': 0
    '2025': 2800
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# Credit value per qualifying dependent
value_dep:
  value:
    '2014': 0
    '2020': 1100
    '2021': 1400
    '2022': 0
    '2025': 2800
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# AGI phaseout threshold, joint returns
po_thresh_married:
  value: 
    '2014': 150000
    '2025': Inf

# AGI phaseout threshold, head of household returns
po_thresh_head:
  value: 
    '2014': 112500
    '2025': Inf
