---
indexation_defaults:
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year:
    '2014': 1987
    '2018': 2017
    '2024': 2023
  i_direction: -1
  i_increment: 50

# Base value for single filers
value_single:
  value:
    '2014': 3000
    '2018': 12000
    '2024': 50000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
# Base value for HOH filers
value_head:
  value:
    '2014': 4400
    '2018': 18000
    '2024': 50000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
