---

# Maximum deductible business loss
bus_loss_limit_married:
  value:
    '2014': Inf
    '2022': 500000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
# Whether tipped income is deductible from gross income
tip_deduction:
  value: 
    '2014': 0
    '2025': 1
    '2029': 0

# Whether FLSA-eligible overtime income is deductible from gross income
ot_deduction:
  value: 
    '2014': 0
    '2025': 1
    '2029': 0

# OT deduction applying to only the "half" of "time and a half"
ot_deduction_half:
  value:
    '2014': 0
    '2025': 1
    '2029': 0
    
# Whether auto loan interest is deductible from gross income
auto_int_deduction:
  value: 
    '2014': 0
    '2025': 1
    '2029': 0
