---

# AOC credit rate per dollar of qualifying expenses
aoc_rates:
  value: 
    '2014': [1.0, 0.25, 0.0]
    '2025': [0.0, 0.0, 0.0]

# LLC credit rate per dollar of qualifying expenses
llc_rates:
  value: 
    '2014': [0.2, 0.0]
    '2025': [0.0, 0.0]
