---
indexation_defaults:
  i_measure:
    '1986': cpi
    '2017': chained_cpi
  i_base_year:
    '2014': 2011
    '2018': 2017
    '2026': 2011
  i_direction: 0
  i_increment: 100

filing_status_mapper:
  exempt:
    '1': exempt_single
    '2': exempt_married
    '3': exempt_married / 2
    '4': exempt_single
  exempt_po_thresh:
    '1': exempt_po_thresh_single
    '2': exempt_po_thresh_married
    '3': exempt_po_thresh_mfs
    '4': exempt_po_thresh_single
  brackets:
    '1': brackets_single
    '2': brackets_single
    '3': brackets_single / 2
    '4': brackets_single

# Whether exemptions are a preference item (i.e. added back from taxable income)
pe_pref:
  value: 1

# AMT exemption, single filers
exempt_single:
  value:
    '2014': 50600
    '2018': 70300
    '2026': 50600
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# AMT exemption, joint filers
exempt_married:
  value:
    '2014': 78750
    '2018': 109400
    '2026': 78750
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# AMT taxable income threshold above which exemption phases out, single filers
exempt_po_thresh_single:
  value: 
    '2014': 112500
    '2018': 500000
    '2026': 112500
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
# AMT taxable income threshold above which exemption phases out, married filers
exempt_po_thresh_married:
  value:
    '2014': 150000
    '2018': 1000000
    '2026': 150000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default
  
# AMT taxable income threshold above which exemption phases out, married filing separately returns
exempt_po_thresh_mfs:
  value:
    '2014': 75000
    '2018': 500000
    '2026': 75000
  i_measure: default
  i_base_year: default
  i_direction: default
  i_increment: default

# Exemption phaseout rate
exempt_po_rate:
  value: 0.25

# AMT rates
rates:
  value: [0.26, 0.28]

# AMT brackets, single filers
brackets_single:
  value:
    '2014': [0, 175000]
  i_measure: default
  i_base_year: [2011, 2011]
  i_direction: [-1, -1]
  i_increment: [100, 100]
