---

filing_status_mapper:
  tip_ded_po_thresh:
    '1': tip_ded_po_thresh_single
    '2': tip_ded_po_thresh_single * 2
    '3': tip_ded_po_thresh_single
    '4': tip_ded_po_thresh_single
  ot_ded_po_thresh:
    '1': ot_ded_po_thresh_single
    '2': ot_ded_po_thresh_single * 2
    '3': ot_ded_po_thresh_single
    '4': ot_ded_po_thresh_single
  ot_ded_limit:
    '1': ot_ded_limit_single
    '2': ot_ded_limit_single * 2
    '3': ot_ded_limit_single
    '4': ot_ded_limit_single
  senior_ded_po_thresh:
    '1': senior_ded_po_thresh
    '2': senior_ded_po_thresh * 2
    '3': senior_ded_po_thresh
    '4': senior_ded_po_thresh

# Maximum deductible tips
tip_ded_limit:
  value: 
    '2014': 0
    '2025': 25000
    '2029': 0
    
# AGI threshold for tip deduction phaseout, non-joint returns
tip_ded_po_thresh_single:
  value:
    '2014': Inf
    '2025': 150000
    '2029': Inf
    
# Phaseout rate for tip deduction
tip_ded_po_rate:
  value: 
    '2014': 0
    '2025': 0.1
    '2029': 0
    
# Whether OT deduction applies only to the "half" of "time and a half"
ot_ded_half:
  value:
    '2014': 0
    '2025': 1
    '2029': 0
    
# Maximum deductible OT
ot_ded_limit_single:
  value:
    '2014': 0
    '2025': 12500
    '2029': 0
    
# AGI threshold for OT deduction phaseout, non-joint returns
ot_ded_po_thresh_single:
  value: 
    '2014': Inf
    '2025': 150000
    '2029': Inf
    
# Phaseout rate for OT deduction
ot_ded_po_rate:
  value: 
    '2014': 0
    '2025': 0.1
    '2029': 0

# Senior bonus deduction value
senior_ded_value:
  value: 
    '2014': 0
    '2025': 6000
    '2029': 0

# Phaseout rate for senior bonus deduction
senior_ded_po_rate:
  value: 
    '2014': 0
    '2025': 0.06
    '2029': 0
