---

# Deduction rate
rate:
  value: 
    '2014': 0.0
    '2018': 0.2
  
# Taxable income phaseout range for SSTBs, single filers
po_range_sstb_single:
  value: 
    '2014': 50000
    '2026': 75000

# Taxable income phaseout range for non-SSTBs, single filers
po_range_non_sstb_single:
  value: 
    '2014': 50000
    '2026': 75000
