---
  
# Whether tipped income is deductible from gross income
tip_deduction:
  value: 
    '2014': 0
    '2025': 1

# Whether FLSA-eligible overtime income is deductible from gross income
ot_deduction:
  value: 
    '2014': 0
    '2025': 1
