---

# Whether SSN is required to qualify for CTC
need_ssn:
  value:
    '2014': 0
    '2018': 1
    '2021': 0
    '2022': 1

# Maximum credit value per "young" child
value_young:
  value: 
    '2014': [1000, 0]
    '2018': [2000, 0]
    '2021': [2000, 1600]
    '2022': [2000, 0]
    '2026': [4200, 0]

# Maximum credit value per "old" child
value_old:
  value:
    '2014': [1000, 0]
    '2018': [2000, 0]
    '2021': [2000, 1000]
    '2022': [2000, 0]
    '2026': [3000, 0] 

# Maximum age to qualify as an "old" child
old_age_limit:
  value:
    '2014': 16
    '2021': 17
    '2022': 16
    '2026': 17

# AGI threshold above which credit value phases out, single filers
po_thresh_single:
  value:
    '2014': [75000, Inf]
    '2018': [200000, Inf]
    '2021': [200000, 75000]
    '2022': [200000, Inf]
    
# AGI threshold above which credit value phases out, joint filers
po_thresh_married:
  value:
    '2014': [110000, Inf] 
    '2018': [400000, Inf]
    '2021': [400000, 150000]
    '2022': [400000, Inf]
    
# AGI threshold above which credit value phases out, HoH filers
po_thresh_head:
  value:
    '2014': [75000, Inf]
    '2018': [200000, Inf]
    '2021': [200000, 112500]
    '2022': [200000, Inf]


# Maximum refundable CTC per young qualifying child (inf implies maximum refund 
# is equal to the credit value)
max_refund_young:
  value:
    '2014': Inf
    '2018': 1400
    '2021': Inf
    '2022': 1400
    '2026': Inf
  i_measure: 
    '1987': cpi
    '2017': chained_cpi
  i_base_year: 2017
  i_direction: -1
  i_increment: 100
  
# Maximum refundable CTC per old qualifying child (inf implies maximum refund 
# is equal to the credit value)
max_refund_old:
  value:
    '2014': Inf
    '2018': 1400
    '2021': Inf
    '2022': 1400
    '2026': Inf
  i_measure: 
    '1987': cpi
    '2017': chained_cpi
  i_base_year: 2017
  i_direction: -1
  i_increment: 100

# Whether phase-in type is a rate (0 means range)
pi_type:
  value: 
    '2014': 1
    '2026': 0

# Phase-in range
pi_range: 
  value: 10000
  i_measure: 
    '1987': cpi
    '2017': chained_cpi
  i_base_year: 2025 
  i_direction: -1
  i_increment: 100

# Earned income threshold above which CTC phases in
pi_thresh:
  value:
    '2014': 3000
    '2018': 2500
    '2026': 0
