---

filing_status_mapper:
  young_po_thresh:
    '1': young_po_thresh_single
    '2': young_po_thresh_joint
    '3': young_po_thresh_single
    '4': young_po_thresh_single
  old_po_thresh:
    '1': old_po_thresh_single
    '2': old_po_thresh_joint
    '3': old_po_thresh_single
    '4': old_po_thresh_single
  young_po_rate:
    '1': young_po_rate_single
    '2': young_po_rate_joint
    '3': young_po_rate_single
    '4': young_po_rate_single
  old_po_rate:
    '1': old_po_rate_single
    '2': old_po_rate_joint
    '3': old_po_rate_single
    '4': old_po_rate_single

# Young dependents: credit rates 
young_rate:
  value:
    '2014': [0.2, 0.15, 0.0]
    '2021': [0.2, 0.3, 0.0]
    '2022': [0.2, 0.15, 0.0]
    '2026': [0.2, 0.15, 0.15]
  
# Young dependents: AGI threshold above which credit rate begins phasing out from max to min
young_po_thresh_single:
  value:
    '2014': [Inf, 15000, 0]
    '2021': [400000, 125000, 0]
    '2022': [Inf, 15000, 0]
    '2026': [Inf, 75000, 15000]

# Young dependents: AGI threshold above which credit rate begins phasing out from max to min
young_po_thresh_joint:
  value:
    '2014': [Inf, 15000, 0]
    '2021': [400000, 125000, 0]
    '2022': [Inf, 15000, 0]
    '2026': [Inf, 150000, 15000]

# Young dependents: rate at which credit rate phases out with AGI
young_po_rate_single:
  value: 
    '2014': [0.0, 0.000005, 0.0]
    '2021': [0.000005, 0.000005, 0.0]
    '2022': [0.0, 0.000005, 0.0]
    '2026': [0.0, 0.000005, 0.000005]

# Young dependents: rate at which credit rate phases out with AGI
young_po_rate_joint:
  value: 
    '2014': [0.0, 0.000005, 0.0]
    '2021': [0.000005, 0.000005, 0.0]
    '2022': [0.0, 0.000005, 0.0]
    '2026': [0.0, 0.0000025, 0.000005]
    
# Old dependents: credit rates 
old_rate:
  value:
    '2014': [0.2, 0.15, 0.0]
    '2021': [0.2, 0.3, 0.0]
    '2022': [0.2, 0.15, 0.0]
    '2026': [0.2, 0.15, 0.15]
  
# Old dependents: AGI threshold above which credit rate begins phasing out from max to min
old_po_thresh_single:
  value:
    '2014': [Inf, 15000, 0]
    '2021': [400000, 125000, 0]
    '2022': [Inf, 15000, 0]
    '2026': [Inf, 75000, 15000]

# Old dependents: AGI threshold above which credit rate begins phasing out from max to min
old_po_thresh_joint:
  value:
    '2014': [Inf, 15000, 0]
    '2021': [400000, 125000, 0]
    '2022': [Inf, 15000, 0]
    '2026': [Inf, 150000, 15000]

# Old dependents: rate at which credit rate phases out with AGI
old_po_rate_single:
  value: 
    '2014': [0.0, 0.000005, 0.0]
    '2021': [0.000005, 0.000005, 0.0]
    '2022': [0.0, 0.000005, 0.0]
    '2026': [0.0, 0.000005, 0.000005]

# Old dependents: rate at which credit rate phases out with AGI
old_po_rate_joint:
  value: 
    '2014': [0.0, 0.000005, 0.0]
    '2021': [0.000005, 0.000005, 0.0]
    '2022': [0.0, 0.000005, 0.0]
    '2026': [0.0, 0.0000025, 0.000005]

